
%
% Bad Romance
%
% By: Lady Gaga
% Writers: Lady Gaga, Nadir Khayat
%

%#ok<*BDSCA>
clc

NoteInit_fr

V0 = V-0; V1 = V-1; V2 = V-2; V3 = V-3; V4 = V-4; 

MARKER_INTRO = Note( 'marker', 'Intro' );
MARKER_A = Note( 'marker', 'HA HA HAHAHA' );
MARKER_B = Note( 'marker', 'Couplet 1' );
MARKER_C = Note( 'marker', 'Refrain 1' );
MARKER_D = Note( 'marker', 'HA HA HAHAHA 2' );
MARKER_E = Note( 'marker', 'Couplet 2' );
MARKER_F = Note( 'marker', 'Refrain 2' );
MARKER_G = Note( 'marker', 'HA HA HAHAHA 3' );
MARKER_H = Note( 'marker', 'Pont 1' );
MARKER_I = Note( 'marker', 'Pont 2' );
MARKER_J = Note( 'marker', 'Refrain 3' );
MARKER_K = Note( 'marker', 'Coda' );
MARKER_END = Note( 'marker', 'End' );

%% MAIN

P = [ S:R bar ];

MAIN = [ ...
	MARKER_INTRO S:B bar P*8 ...
	MARKER_A P*8 ...
	MARKER_B P*20 ...
	MARKER_C P*16 ...
	MARKER_D P*4 ...
	MARKER_E P*20 ...
	MARKER_F P*16 ...
	MARKER_G P*8 ...
	MARKER_H P*8 ...
	MARKER_I P*16 ...
	MARKER_J P*8 ...
	MARKER_K P*12 ...
	MARKER_END
	];

%% CHANT

HOHOHO = [ Note('+') ...
	~[ do:C re:C mi:C do:C bar ...
	fa:N' mi:C fa:C mi:C re:N bar ...
	re:N ] S:C ~[ -si:C do:N re:C ] S:C bar ...
	mi:N ~mi:'.':C mi:'.':C ~[ mi:C re:N do:C bar ...
	do:N ] S:N ];

HAHA = [ Note('+') ...
	~-la:C S:C -la:N mi:C mi:'.':C ~[ fa:C mi:C ] bar ...
	S:C -la:'.':C -la:N mi:'.':C mi:'.':C ~[ fa:C mi:C ] bar ...
	-la:C S:C -la:N mi:C mi:'.':C ~[ fa:C mi:C ] bar ...
	S:C do:'.':C ~[ do:C -la:C do:C ] S:C do:N bar ];

COUPLET = [ Note('') ...
	S:C sol:'.':C la:C ~sol:C la:C la:N la:'.':C bar ...
	+do:C ~la:C sol:C la:C ~sol:N' S:C bar ...
	S:C la:'.':C la:C ~sol:'.':C la:C ~sol:C la:C ~sol:C bar ...
	+do:C ~la:C sol:C ~la:N ~mi:C sol:C ~la:C bar ...
	la:[B C] S:C S:N bar ...
	+mi:'.':N +do:'.':N la:C ~mi:'.':C sol:C ~la:C bar ...
	la:[B C] S:C S:N bar ...
	S:R bar ...
	S:C +do:'.':C +do:C ~la:C +do:C +do:N la:'.':C bar ...
	+do:C +do:'.':C la:C +do:N S:[C N] bar ...
	S:C +do:'.':C +do:C ~la:'.':C +do:C ~la:'.':C +do:C ~la:'.':C bar ...
	+do:C ~la:C la:C la:C ~sol:C ~mi:'.':C sol:C ~la:C bar ...
	la:[B C] S:C S:N bar ...
	+mi:'.':N +do:'.':N la:C ~mi:'.':C sol:C ~la:C bar ...
	la:[B C] S:C S:N bar ...
	S:R bar ...
	S:C' [sol sol sol sol fa S mi ~mi S ].*D S:N bar ...
	S:C [ sol sol sol sol sol fa S mi ~mi S ].*D S:N bar ...
	S:C la:'.':C la:C ~sol:'.':C la:N S:C sol:'.':C bar ...
	la:N ~sol:C ~-la:N' S:N bar ];

REFRAIN = [ Note('+') ...
	S:C la:'.':C la:C la:'.':C la:C la:N sol:C bar ...
	sol:C sol:'.':C sol:C ~re:C ~re:'.':C re:C ~re:'.':C mi:C bar ...
	~mi:'.':C mi:'.':C mi:C mi:'.':C sol:N re:C ~mi:D ~re:D bar ...
	do:B S:B bar ...
	S:C la:'.':C la:C la:'.':C la:C la:C la:C sol:C bar ...
	sol:C sol:'.':C sol:C ~re:C ~re:'.':C re:C ~re:'.':C mi:C bar ...
	~mi:'.':C mi:'.':C mi:C mi:'.':C laB:N re:C ~mi:D ~re:D bar ...
	do:B ];

PONT1 = [ Note('') ...
	sol:N sol:N sol:'.':C sol:'.':C sol:C sol:'.':C bar ...
	sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':D sol:D ~sol:C sol:'.':C bar ...
	sol:N sol:N sol:'.':C sol:'.':C sol:C sol:'.':C bar ...
	sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':D sol:D ~sol:C sol:'.':C bar ...
	sol:N sol:N sol:'.':C sol:'.':C sol:C sol:'.':C bar ...
	sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':D sol:D ~sol:C sol:'.':C bar ...
	sol:N sol:N sol:'.':C sol:'.':C sol:C sol:'.':C bar ...
	sol:'.':C sol:'.':C sol:D sol:D S:D sol:D S:D sol:C' S:C sol:C bar ];

PONT2 = [ Note('') ...
	~fa:C S:C +do:C ~si:C S:C sol:C S:C la:C bar ...
	~la:N +do:C +do:C ~si:C si:C sol:C ~mi:C bar ...
	~mi:N +do:C ~si:C S:C sol:C S:C la:C bar ...
	~la:N +mi:C +mi:'.':C +mi:C +mi:C ~+re:C ~+do:C bar ...
	S:N +do:C ~si:C S:C sol:C S:C la:C bar ...
	~la:N +do:C +do:C ~si:C si:C sol:C ~mi:C bar ...
	~mi:N +do:C ~si:C S:C sol:C S:C la:C bar ...
	~la:N +mi:C +mi:'.':C +mi:C +mi:C ~+re:C ~+do:C bar ...
	~+do:B' ~+do:C S:C bar ...
	Note('+') S:N mi:C mi:'.':C mi:C mi:C sol:C ~do:C bar ...
	~do:B S:B bar ...
	S:N +do:C +do:'.':C +do:C +do:C ~si:C ~la:C bar ...
	~la:C ~sol:D ~fa:D ~fa:B S:N bar ...
	S:C +do:'.':C +do:C ~la:'.':C +do:C ~la:C ~+do:N bar ...
	S:R bar ...
	S:C +do:'.':C +do:C ~la:'.':C +do:C ~la:C ~+do:N bar ];
	
CODA = [ Note('+') ...
	[ S:R bar ...
	S:C +do:'.':C +do:C ~la:'.':C +do:C ~la:C ~+do:N bar ]*3 ...
	S:R bar ...
	S:R bar ];

CHANT = [ ...
	MARKER_INTRO HOHOHO*2 S:B bar ...
	MARKER_A HAHA*2 ...
	MARKER_B COUPLET ...
	MARKER_C REFRAIN HOHOHO*2 S:B bar ...
	MARKER_D HAHA ...
	MARKER_E COUPLET ...
	MARKER_F REFRAIN HOHOHO*2 S:B bar ...
	MARKER_G HAHA*2 ...
	MARKER_H PONT1 ...
	MARKER_I PONT2 ...
	MARKER_J REFRAIN S:B bar ...
	MARKER_K CODA HAHA ...
	MARKER_END ];

%% SYNBRASS

RIFF1 = [ V0:'.':C V0:'.':C V0:'.':C N V0:'.':C V0:'.':C V0:'.':C bar ];
INTRO = [ Note('+') ...
	S:B bar ...
	[fa la +do]*RIFF1 ...
	[sol si +re]*RIFF1 ...
	[laB si +mi]*RIFF1 ...
	[la +do +mi]*RIFF1 ...
	[fa la +do]*RIFF1 ...
	[sol si +re]*RIFF1 ...
	[laB si +mi]*RIFF1 ...
	[la +do +mi]*RIFF1 ];

HAHA = [ Note('--') ...
	S:C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	S:C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C mi:'.':C bar ...
	S:C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	S:C sol:N sol:'.':C S:C sol:N sol:'.':C bar ];

COUPLET1 = [ ...
	P*14 ...
	Note('+') S:[B C] -la+do+mi:'.':C -la+do+mi:'.':C -la+do+mi:'.':C bar ...
	-la+do+mi:'.':C -la+do+mi:'.':C -la+do+mi:'.':C -la+do+mi:C S:B bar ...
	Note('-') [ (-la+do+mi:'.':C)*8 bar ]*4 ];

REFRAIN1 = [ Note('+') ...
	(-fa+-la+do).*[S:'.':C S:'.':C S:'.':C N N S:'.':C] bar ...
	(-sol+-si+re).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-la+do+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-la+do+mi).*[S:'.':C S:'.':C S:'.':C N] (mi+la++do).*[S:'.':C S:'.':C S:C] bar ...
	(-fa+-la+do).*[S:'.':C S:'.':C S:'.':C N N S:'.':C] bar ...
	(-sol+-si+re).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-laB+-si+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C] -la+-si+mi:'.':C bar ...
	(-la+do+mi).*[S:'.':C S:'.':C S:'.':C N] (mi+la++do).*[S:'.':C S:'.':C S:C] bar ];

COUPLET2 = [ ...
	P*16 ...
	Note('-') [ (-la+do+mi:'.':C)*8 bar ]*4 ];

REFRAIN2 = [ Note('+') ...
	(-fa+-la+do).*[S:'.':C S:'.':C S:'.':C N N S:'.':C] bar ...
	(-sol+-si+re).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-la+do+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-la+do+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:C] bar ...
	(-fa+-la+do).*[S:'.':C S:'.':C S:'.':C N N S:'.':C] bar ...
	(-sol+-si+re).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-laB+-si+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C] -la+-si+mi:'.':C bar ...
	(-la+do+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:C] bar ];
REFRAIN2_ = [ Note('+') ...
	(-fa+-la+do).*[S:'.':C S:'.':C S:'.':C N N S:'.':C] bar ...
	(-sol+-si+re).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-la+do+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-la+do+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:C] bar ...
	(-fa+-la+do).*[S:'.':C S:'.':C S:'.':C N N S:'.':C] bar ...
	(-sol+-si+re).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C] bar ...
	(-laB+-si+mi).*[S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C] -la+-si+mi:'.':C bar ...
	P ];

PONT1 = [ ...
	Note('') [ (-la+do+mi:'.':C)*8 bar ]*8 ];
	
SYNTHBRASS = [ ...
	MARKER_INTRO INTRO ...
	MARKER_A P*4 HAHA ...
	MARKER_B COUPLET1 ...
	MARKER_C REFRAIN1*2 ...
	MARKER_D HAHA ...
	MARKER_E COUPLET2 ...
	MARKER_F REFRAIN1*2 ...
	MARKER_G HAHA*2 ...
	MARKER_H PONT1 ...
	MARKER_I REFRAIN2 REFRAIN2_ ...
	MARKER_J REFRAIN2 ...
	MARKER_K REFRAIN2 P*4 ...
	MARKER_END ];
	
%% BASSE

RIFF1 = [ V:'.':C V:C ~V:'.':C V:'.':C S:C V:C ~V:'.':C V:'.':C bar ];
HOHO1 = [ Note('---') ...
	fa*RIFF1 ...
	sol*RIFF1 ...
	la*RIFF1 ...
	+do*RIFF1 ];
HOHO2 = [ Note('---') ...
	fa*RIFF1 ...
	sol*RIFF1 ...
	laB*RIFF1 ...
	la*RIFF1 ];
HOHO2_ = [ Note('---') ...
	fa*RIFF1 ...
	sol*RIFF1 ...
	laB*RIFF1 ...
	P ];

HAHA_ = [ Note('---') ...
	fa.*[ S:'.':C S:'.':C S:'.':N S:'.':N ] S:N bar P*3 ];
HAHA = [ Note('--') ...
	-la:'.':C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	-la:'.':C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C mi:'.':C bar ...
	-la:'.':C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	S:C sol:N sol:'.':C S:C sol:N sol:'.':C bar ];
HAHA2 = [ Note('--') ...
	S:C -la:'.':C S:C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	S:C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	S:C -la:'.':C S:C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	S:C sol:N sol:'.':C S:C sol:N sol:'.':C bar ];

RIFF2 = [ S:C V1:C ~V1:'.':C V2:'.':C S:C V3:C ~V3:'.':C V4:'.':C bar ];
COUPLET1 = [ Note('--')...
	[ -la -la -la -la ]*RIFF2 ...
	[ do do fa fa ]*RIFF2 ...
	[ -la -la -la -la ]*RIFF2 ...
	[ do do -sol -sol ]*RIFF2 ...
	[ -la -la -la -la ]*RIFF2 ...
	[ do do fa fa ]*RIFF2 ...
	[ do -la -la -la ]*RIFF2 ...
	[ do do -sol re ]*RIFF2 ];

RIFF4 = [ S:C V1:C S:C V2:C S:C V3:C S:C V4:C bar ];
COUPLET2 = [ Note('--') ...
	[ -la -la -la -la ]*RIFF4 ...
	[ do do fa fa ]*RIFF4 ...
	[ -la -la -la -la ]*RIFF4 ...
	[ do do -sol -sol ]*RIFF4 ...
	[ -la -la -la -la ]*RIFF4 ...
	[ do do fa fa ]*RIFF4 ...
	[ do -la -la -la ]*RIFF4 ...
	[ do do -sol re ]*RIFF4 ];

BASSE = [ ...
	MARKER_INTRO S:B bar P*4 HOHO2 ...
	MARKER_A HAHA_ HAHA ...
	MARKER_B COUPLET1*2 HAHA2 ...
	MARKER_C [HOHO1 HOHO2]*2 ...
	MARKER_D HAHA ...
	MARKER_E COUPLET2*2 HAHA2 ...
	MARKER_F [HOHO1 HOHO2]*2 ...
	MARKER_G HAHA*2 ...
	MARKER_H HAHA2*2 ...
	MARKER_I HOHO1 HOHO2 HOHO1 HOHO2_ ...
	MARKER_J HOHO1 HOHO2 ...
	MARKER_K HOHO1 HOHO2 P*4 ...
	MARKER_END ];

%% OBStrings

HOHO1__ = ~[ ~do:B la:B bar ...
	re:B' fa:N bar ...
	mi:B' laB:N bar ...
	mi:B +do:N sol:N bar ];
HOHO1 = [ Note('') HOHO1__ / -HOHO1__ ];
	
HOHO1__ = ~[ ~do:B la:B bar ...
	re:B' fa:N bar ...
	mi:B' laB:N bar ...
	P ];
HOHO1_ = [ Note('') HOHO1__ / -HOHO1__ ];

HOHO2__ = ~[ ~do:B la:B bar ...
	re:B' fa:N bar ...
	mi:B' sol:N bar ...
	mi:B +do:N sol:N bar ];
HOHO2 = [ Note('') HOHO2__ / -HOHO2__ ];

OBSTRINGS = [ ...
	MARKER_INTRO S:B bar HOHO1*2 ...
	MARKER_A P*8 ...
	MARKER_B P*20 ...
	MARKER_C HOHO2 HOHO1 HOHO2 HOHO1 ...
	MARKER_D P*4 ...
	MARKER_E P*20 ...
	MARKER_F HOHO2 HOHO1 HOHO2 HOHO1 ...
	MARKER_G P*8 ...
	MARKER_H P*8 ...
	MARKER_I HOHO2 HOHO1 HOHO2 HOHO1_ ...
	MARKER_J HOHO2 HOHO1 ...
	MARKER_K HOHO2 HOHO1 P*4 ...
	MARKER_END ];

%% POLY


INTRO_ = [ ...
	fa:R bar ...
	sol:R bar ...
	laB:R bar ...
	la:R bar ];
INTRO = [ Note('--') S:B bar ...
	(INTRO_ / -INTRO_)*2 ];

RIFF1 = [ V:'.':C V:C ~V:'.':C V:'.':C S:C V:C ~V:'.':C V:'.':C bar ];
HOHO_ = [ ...
	fa*RIFF1 ...
	sol*RIFF1 ...
	la*RIFF1 ...
	+do*RIFF1 ];
HOHO1 = [ Note('--') HOHO_ / -HOHO_ ];
HOHO_ = [ ...
	fa*RIFF1 ...
	sol*RIFF1 ...
	laB*RIFF1 ...
	la*RIFF1 ];
HOHO2 = [ Note('--') HOHO_ / -HOHO_ ];
HOHO_ = [ ...
	fa*RIFF1 ...
	sol*RIFF1 ...
	laB*RIFF1 ...
	P ];
HOHO2_ = [ Note('--') HOHO_ / -HOHO_ ];

HAHA = [ Note('--') ...
	--la:'.':C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	--la:'.':C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C mi:'.':C bar ...
	--la:'.':C -la:'.':C do:'.':C do:'.':C mi:'.':C mi:'.':C fa:'.':C fa:'.':C bar ...
	-sol:'.':C sol:N sol:'.':C -sol:'.':C sol:N sol:'.':C bar ];

RIFF2 = [ S:C V1:C ~V1:'.':C V2:'.':C S:C V3:C ~V3:'.':C V4:'.':C bar ];
COUPLET1 = [ Note('--')...
	[ -la -la -la -la ]*RIFF2 ...
	[ do do fa fa ]*RIFF2 ...
	[ -la -la -la -la ]*RIFF2 ...
	[ do do -sol -sol ]*RIFF2 ...
	[ -la -la -la -la ]*RIFF2 ...
	[ do do fa fa ]*RIFF2 ...
	[ do -la -la -la ]*RIFF2 ...
	[ do do -sol re ]*RIFF2 ];

RIFF4 = [ S:C V1:C S:C V2:C S:C V3:C S:C V4:C bar ];
COUPLET2 = [ Note('--') ...
	[ -la -la -la -la ]*RIFF4 ...
	[ do do fa fa ]*RIFF4 ...
	[ -la -la -la -la ]*RIFF4 ...
	[ do do -sol -sol ]*RIFF4 ...
	[ -la -la -la -la ]*RIFF4 ...
	[ do do fa fa ]*RIFF4 ...
	[ do -la -la -la ]*RIFF4 ...
	[ do do -sol re ]*RIFF4 ];

POLY = [ ...
	MARKER_INTRO INTRO ...
	MARKER_A P*4 HAHA ...
	MARKER_B COUPLET1*2 P*4 ...
	MARKER_C [HOHO1 HOHO2]*2 ...
	MARKER_D HAHA ...
	MARKER_E COUPLET2*2 P*4 ...
	MARKER_F [HOHO1 HOHO2]*2 ...
	MARKER_G HAHA*2 ...
	MARKER_H P*8 ...
	MARKER_I HOHO1 HOHO2 HOHO1 HOHO2_ ...
	MARKER_J HOHO1 HOHO2 ...
	MARKER_K HOHO1 HOHO2 P*4 ...
	MARKER_END ];

%% CHOEURS

CHOEURS = [ ...
	~MARKER_G P*5 Note('-') ...
	S:C -la:'.':C -la:N mi:'.':C mi:'.':C fa:C ~mi:'.':C bar ...
	-la:N do:N mi:'.':C mi:'.':C fa:C ~mi:'.':C bar ...
	P MARKER_H ];

%% SAW

HAHAHA = [ Note('+') ...
	S:C mi:'.':C S:C mi:'.':C S:C mi:'.':C S:C miB:'.':C bar ...
	S:C mi:'.':C S:C mi:'.':C S:C mi:'.':C S:C fa:'.':C bar ...
	S:C mi:'.':C S:C mi:'.':C S:C mi:'.':C S:C miB:'.':C bar ...
	S:C mi:'.':C S:C mi:'.':C S:B bar ...
	S:C mi:'.':C S:C mi:'.':C S:C mi:'.':C S:C miB:'.':C bar ...
	S:C mi:'.':C S:C mi:'.':C S:C mi:'.':C S:C fa:'.':C bar P P ];

pitch = @(varargin) Note('Pitch',varargin{:});
pitch2 = @(varargin) Note('Pitch','quad',varargin{:});
COUPLET = [ Note('+') ...
	pitch('#####') pitch2('b',B) S:D --la+-la:[D C B'] pitch2('0') bar ...
	pitch('##') ~-do+do:N pitch2('0') pitch('####') ~-do+do:'|':N pitch2('0') pitch2('bbbbbbb',N') ~--si+-si:B bar ...
	pitch2('#####') pitch2('b',B) ~--la+-la:R pitch2('0') bar ...
	pitch('#####') pitch2('b',B) --la+-la:R pitch2('0') bar ];

PONT = [ Note('') ...
	S:B ~[ do:C re:C mi:C do:C bar ...
	fa:N' mi:C fa:C mi:C re:N bar ...
	re:N -si:N do:N re:N bar ...
	mi:N' re:C mi:C re:N do:C bar ...
	do:N ] S:N ~[ do:C re:C mi:C do:C bar ...
	fa:N' mi:C fa:C mi:C re:N bar ...
	re:N -si:N do:N re:N bar ...
	mi:N' re:C mi:C re:N do:C ] bar ...
	S:R bar ];

SAW = [ ...
	MARKER_INTRO S:B bar P*8 ...
	MARKER_A HAHAHA ...
	MARKER_B [ P*4 COUPLET ]*2 P*4 ...
	MARKER_C P*16 ...
	MARKER_D COUPLET ...
	MARKER_E [ P*4 COUPLET ]*2 P*4 ...
	MARKER_F P*16 ...
	MARKER_G P*4 COUPLET ...
	MARKER_H P*8 ...
	MARKER_I P*7 PONT ...
	MARKER_J P*8 ...
	MARKER_K P*12 ...
	MARKER_END
	];

%% SQUARE

RIFF = [ S:C V1:C S:C V2:C S:C V3:C S:C V4:C bar ];
COUPLET = [ Note('') ...
	[ do do do do ]*RIFF ...
	[ mi mi la la ]*RIFF ...
	[ do do do do ]*RIFF ...
	[ mi mi -si fa ]*RIFF ];

SQUARE = [ ~MARKER_E COUPLET P*4 COUPLET P*8 MARKER_F ];

%% PIANO

REFRAIN = [ Note('+') ...
	(fa+la++do).*[ S:'.':C S:'.':C S:'.':C N N S:'.':C ] bar ...
	(sol+si++re).*[ S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C ] bar ...
	(la++do++mi).*[ S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C ] bar ...
	(la++do++mi).*[ S:'.':C S:'.':C S:'.':C N ] (+mi++la+++do).*[ S:'.':C S:'.':C S:'.':C ] bar ];
REFRAIN_ = [ Note('+') ...
	(fa+la++do).*[ S:'.':C S:'.':C S:'.':C N N S:'.':C ] bar ...
	(sol+si++re).*[ S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C ] bar ...
	(la++do++mi).*[ S:'.':C S:'.':C S:'.':C N S:'.':C S:'.':C S:'.':C ] bar ...
	P ];

HAHA = [ Note('+') ...
	(-la+do+mi).*(S:'.':C)*8 bar ...
	(-la+do+mi).*(S:'.':C)*8 bar ...
	(-la+do+mi).*(S:'.':C)*8 bar ...
	(do+mi+la).*(S:'.':C)*8 bar ];
	

PIANO = [ ...
	~MARKER_C REFRAIN*4 ...
	MARKER_D HAHA ...
	MARKER_E P*20 ...
	MARKER_F REFRAIN*4 ...
	MARKER_G HAHA*2 ...
	MARKER_H P*8 ...
	MARKER_I REFRAIN*3 REFRAIN_ ...
	MARKER_J REFRAIN*2 ...
	MARKER_K REFRAIN*2 P*4 ...
	MARKER_END
	];

%% CHOEURS2

INTRO = [ Note('') ...
	S:B bar ...
	P*3 ...
	S:B ~[ do:C re:C mi:C do:C bar ...
	fa:N' mi:C fa:C mi:C re:N bar ...
	re:N ] S:C ~[ -si:C do:N re:C ] S:C bar ...
	P*2 ];

COUPLET = [ Note('') ...
	mi+sol:N do+mi:N -la+do:C -mi+-sol:'.':C -sol+-la:'.':C do+mi:C bar ...
	do+mi:B S:B bar ];

R1 = [ Note('') ...
	S:B ~[ do:C re:C mi:C do:C bar ...
	fa:B S:B ] bar ];
R2 = [ Note('') ...
	do:N' do:'.':C ~[ do:C -la:N -sol:C bar ...
	-sol:N ] S:B' bar ];
R3 = [ Note('') ...
	-si:N' -si:'.':C ~[ do:C -si:N -la:C bar ...
	-la:N ] S:B' bar ];

HAHA = [ Note('-') ...
	P ...
	S:C -la:'.':C -la:N mi:'.':C mi:'.':C fa:C ~mi:C bar ...
	-la:N do:N mi:'.':C mi:'.':C fa:C ~mi:C bar ...
	P ];

CHOEURS2 = [ ...
	MARKER_INTRO INTRO ...
	~MARKER_B P*5 COUPLET P*7 COUPLET P*4 ...
	MARKER_C P*3 R1 P*2 R1 P R2 P*2 R3 ...
	MARKER_D HAHA ...
	MARKER_E P*5 COUPLET P*7 COUPLET P*4 ...
	MARKER_F P*3 R1 P*2 R1 P R2 P*2 R3 ...
	MARKER_G HAHA HAHA ...
	~MARKER_I P*7 ...
	Note('') S:B ~[ do:C re:C mi:C do:C bar ...
	fa:N' mi:C fa:C mi:C re:N bar ...
	re:N -si:N do:N re:N bar ...
	mi:N' re:C mi:C re:N do:C bar ...
	do:N ] S:N ~[ do:C re:C mi:C do:C bar ...
	fa:N' mi:C fa:C mi:C re:N bar ...
	re:N -si:N do:N re:N bar ...
	mi:N' re:C mi:C re:N do:C ] bar ...
	P ...
	MARKER_J P*3 ...
	Note('') S:B ~[ do:C re:C mi:C do:C bar ...
	fa:B ] S:B bar ...
	P*2 ...
	S:B ~[ do:C re:C mi:C do:C bar ...
	MARKER_K fa:N' mi:C fa:C mi:N re:C bar ...
	re:N -si:N do:N re:N bar ...
	do+mi:N' ] do+mi:'.':C ~[ do+mi:C -la+re:N -sol+do:C bar ...
	-sol+do:N ] S:N ~[ do:C re:C mi:C do:C bar ...
	fa:N' mi:C fa:C mi:N re:C bar ...
	re:N -si:N do:N re:N bar ...
	-si+mi:N' ] -si+mi:'.':C do+mi:C ~-si+reB:N -la+-si:C bar ...
	~-la+-si:N S:B' bar ...
	P*4 ...
	MARKER_END ...
	];

%% SAW2

SAW2 = [ Note('') ...
	~MARKER_D ...
	[ do S do S do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ do S do S do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ do S do S do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ S S do do do do do do do do do do do do do do ].*(S:'.':D) bar ...
	MARKER_E [ do do do do ].*(S:'.':D) S:B' bar ...
	~MARKER_G [ do S do S do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ do S do S do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ do S do S do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ S S do do do do do do do do do do do do do do ].*(S:'.':D) bar ...
	[ do do do do do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ do S do S do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ do S do S do S do S do S do S do S do do ].*(S:'.':D) bar ...
	[ S S do do do do do do do do do do do do do do ].*(S:'.':D) bar ...
	MARKER_H [ do do do do ].*(S:'.':D) S:B' bar ];

%% WOODBLOCK

RIFF = [ Note('+++') si:'.':D si:'.':D si:'.':C si:'.':C si:'.':C S:B bar P ];

WOODBLOCK = [ ...
	~MARKER_A P*4 RIFF*2 ...
	MARKER_B RIFF*8 P*4 ...
	MARKER_C RIFF*8 ...
	MARKER_D RIFF*2 ...
	MARKER_E RIFF*8 P*4 ...
	MARKER_F RIFF*8 ...
	MARKER_G RIFF*4 ...
	~MARKER_J RIFF*4 ...
	MARKER_K RIFF*4 P*4 ...
	MARKER_END
	];

%% BASSDRUM

RIFF = [ V:'.':D S:[D C] V:'.':D S:[D C] V:'.':D S:[D C] V:'.':D S:[D C] bar ];
RIFF1000 = [ V:'.':D S:[D C] S:B' bar ];
RIFF1110 = [ V:'.':D S:[D C] V:'.':D S:[D C] V:'.':D S:[D C] S:N bar ];

BASSDRUM = [ ...
	MARKER_INTRO S:B bar P*4 RIFF*4 ...
	MARKER_A P*2 RIFF RIFF1000 RIFF*4 ...
	MARKER_B RIFF*19 RIFF1110 ...
	MARKER_C RIFF*16 ...
	MARKER_D RIFF*4 ...
	MARKER_E RIFF*19 RIFF1110 ...
	MARKER_F RIFF*16 ...
	MARKER_G RIFF*8 ...
	MARKER_H RIFF*3 RIFF1110 RIFF*3 RIFF1110 ...
	MARKER_I RIFF*15 P ...
	MARKER_J RIFF*8 ...
	MARKER_K RIFF*8 P*4 ...
	MARKER_END
	];

%% SNARE

RIFF = [S:N V:'.':D S:[D C] S:N V:'.':D S:[D C] bar ];

SNARE = [ ...
	~MARKER_A P*4 RIFF*4 ...
	MARKER_B RIFF*16 P*4 ...
	MARKER_C RIFF*16 ...
	MARKER_D RIFF*4 ...
	MARKER_E RIFF*16 P*4 ...
	MARKER_F RIFF*16 ...
	MARKER_G RIFF*8 ...
	MARKER_H P*8 ...
	MARKER_I RIFF*15 P ...
	MARKER_J RIFF*8 ...
	MARKER_K RIFF*8 P*4 ...
	MARKER_END
	];

%% HIHAT

RIFF1 = [ S:C V1:'.':C S:C V1:'.':C S:C V1:'.':C S:C V1:'.':C bar ];
RIFF1_ = [ S:C V1:'.':C S:C V1:'.':C S:C V1:'.':C S:N bar ];
RIFF2 = [ V1:'.':C V1:'.':C V2:'.':C V1:'.':C V1:'.':C V1:'.':C V2:'.':C V1:'.':C bar ];

HIHAT = [ ...
	~MARKER_A P*2 RIFF1 P*5 ...
	MARKER_B P*16 RIFF1*3 RIFF1_ ...
	MARKER_C RIFF2*16 ...
	MARKER_D RIFF2*4 ...
	MARKER_E P*16 RIFF1*3 RIFF1_ ...
	MARKER_F RIFF2*16 ...
	MARKER_G RIFF2*8 ...
	MARKER_H RIFF1*3 RIFF1_ RIFF1*3 RIFF1_ ...
	MARKER_I P*16 ...
	MARKER_J RIFF2*8 ...
	MARKER_K RIFF2*8 P*4 ...
	MARKER_END
	];

%% CYMBAL

RIFF = [ V:'.':D S:[D C B'] bar P*3 ];

CYMBAL = [ ...
	~MARKER_C RIFF*4 ...
	MARKER_D RIFF ...
	~MARKER_F RIFF*4 ...
	MARKER_G RIFF*2 ...
	~MARKER_J RIFF*2 ...
	MARKER_K RIFF*2 P*4 ...
	MARKER_END
	];

%% Mute Triangle

RIFF1 = [ S:C V1:'.':C S:C V1:'.':C S:C V1:'.':C S:C V1:'.':C bar ];
RIFF2 = [ S:C V1:'.':C S:C V1:'.':C S:C V1:'.':C S:N bar ];
RIFF = [ RIFF1*3 RIFF2 ];

TRIANGLE = [ ...
	~MARKER_B P*16 RIFF ...
	MARKER_C ~MARKER_E P*16 RIFF ...
	MARKER_F ~MARKER_H RIFF RIFF ...
	MARKER_I ];

%% CACOFONIX

cacofonix( 'BadRomance', 'Tempo', 120, 'DrumKit', 'Electronic', ...
	MAIN, ...
	'Flute', [ DynF CHANT ], ...
	'Synth Brass 1', [ DynMP SYNTHBRASS ], ...
	'Synth Bass 2', [ DynF BASSE ], ...
	'Synth Strings 1', [ DynMF OBSTRINGS ], ...
	'Polysynth Pad', [ DynF POLY ], ...
	'Choir Aahs', [ DynMP CHOEURS ], ...
	'Saw Lead', [ DynP SAW ], ...
	'Square Lead', [ DynF SQUARE ], ...
	'Honky-tonk Piano', [ DynP PIANO ], ...
	'Synth Calliope', [ DynMP CHOEURS2 ], ...
	'Saw Lead', [ DynMP SAW2 ], ...
	'Woodblock', [ DynMF WOODBLOCK ], ...
	'Bass Drum 1', [ DynMF BASSDRUM ], ...
	'Electric Snare', [ DynF SNARE ], ...
	'Closed Hi-Hat', [ DynMF HIHAT ], ...
	'Crash Cymbal 2', [ DynP CYMBAL ], ...
	'Mute Triangle', [ DynMF TRIANGLE ] );

