
%
% Bad Romance
%
% By: Lady Gaga
% Writers: Lady Gaga, Nadir Khayat
%

%#ok<*BDSCA>
clc

NoteInit_fr

MARKER_INTRO = Note( 'marker', 'Intro - 2.3' ); % 2.3
MARKER_A = Note( 'marker', 'HA HA HAHAHA 1 - 11' );
MARKER_B = Note( 'marker', 'Couplet 1 - 19' );
MARKER_C = Note( 'marker', 'Refrain 1 - 39' );
MARKER_D = Note( 'marker', 'HA HA HAHAHA 2 - 55' );
MARKER_E = Note( 'marker', 'Couplet 2 - 59' );
MARKER_F = Note( 'marker', 'Refrain 2 - 79' );
MARKER_G = Note( 'marker', 'HA HA HAHAHA 3 - 95' );
MARKER_H = Note( 'marker', 'Pont 1 - 103' );
MARKER_I = Note( 'marker', 'Pont 2 - 111' );
MARKER_J = Note( 'marker', 'Refrain 3 - 127' );
MARKER_K = Note( 'marker', 'Coda - 135' );
MARKER_END = Note( 'marker', 'End' );

%% MAIN

P = [ S:R bar ];

MAIN = [ ...
	MARKER_INTRO S:B bar P*8 ...
	MARKER_A P*8 ...
	MARKER_B P*20 ...
	MARKER_C P*16 ...
	MARKER_D P*4 ...
	MARKER_E P*20 ...
	MARKER_F P*16 ...
	MARKER_G P*8 ...
	MARKER_H P*8 ...
	MARKER_I P*16 ...
	MARKER_J P*8 ...
	MARKER_K P*12 ...
	MARKER_END
	];

%% CHANT

HOHOHO = [ Note('+') ...
	~[ do:C re:C mi:C do:C bar ...
	fa:N' mi:C fa:C mi:C re:N bar ...
	re:N ] S:C ~[ -si:C do:N re:C ] S:C bar ...
	mi:N ~mi:'.':C mi:'.':C ~[ mi:C re:N do:C bar ...
	do:N ] S:N ];

HAHA = [ Note('+') ...
	~-la:C S:C -la:N mi:C mi:'.':C ~[ fa:C mi:C ] bar ...
	S:C -la:'.':C -la:N mi:'.':C mi:'.':C ~[ fa:C mi:C ] bar ...
	-la:C S:C -la:N mi:C mi:'.':C ~[ fa:C mi:C ] bar ...
	S:C do:'.':C ~[ do:C -la:C do:C ] S:C do:N bar ];

COUPLET = [ Note('') ...
	S:C sol:'.':C la:C ~sol:C la:C la:N la:'.':C bar ...
	+do:C ~la:C sol:C la:C ~sol:N' S:C bar ...
	S:C la:'.':C la:C ~sol:'.':C la:C ~sol:C la:C ~sol:C bar ...
	+do:C ~la:C sol:C ~la:N ~mi:C sol:C ~la:C bar ...
	la:[B C] S:C S:N bar ...
	+mi:'.':N +do:'.':N la:C ~mi:'.':C sol:C ~la:C bar ...
	la:[B C] S:C S:N bar ...
	S:R bar ...
	S:C +do:'.':C +do:C ~la:C +do:C +do:N la:'.':C bar ...
	+do:C +do:'.':C la:C +do:N S:[C N] bar ...
	S:C +do:'.':C +do:C ~la:'.':C +do:C ~la:'.':C +do:C ~la:'.':C bar ...
	+do:C ~la:C la:C la:C ~sol:C ~mi:'.':C sol:C ~la:C bar ...
	la:[B C] S:C S:N bar ...
	+mi:'.':N +do:'.':N la:C ~mi:'.':C sol:C ~la:C bar ...
	la:[B C] S:C S:N bar ...
	S:R bar ...
	S:C' [sol sol sol sol fa S mi ~mi S ].*D S:N bar ...
	S:C [ sol sol sol sol sol fa S mi ~mi S ].*D S:N bar ...
	S:C la:'.':C la:C ~sol:'.':C la:N S:C sol:'.':C bar ...
	la:N ~sol:C ~-la:N' S:N bar ];

REFRAIN = [ Note('+') ...
	S:C la:'.':C la:C la:'.':C la:C la:N sol:C bar ...
	sol:C sol:'.':C sol:C ~re:C ~re:'.':C re:C ~re:'.':C mi:C bar ...
	~mi:'.':C mi:'.':C mi:C mi:'.':C sol:N re:C ~mi:D ~re:D bar ...
	do:B S:B bar ...
	S:C la:'.':C la:C la:'.':C la:C la:C la:C sol:C bar ...
	sol:C sol:'.':C sol:C ~re:C ~re:'.':C re:C ~re:'.':C mi:C bar ...
	~mi:'.':C mi:'.':C mi:C mi:'.':C laB:N re:C ~mi:D ~re:D bar ...
	do:B ];

PONT1 = [ Note('') ...
	sol:N sol:N sol:'.':C sol:'.':C sol:C sol:'.':C bar ...
	sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':D sol:D ~sol:C sol:'.':C bar ...
	sol:N sol:N sol:'.':C sol:'.':C sol:C sol:'.':C bar ...
	sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':D sol:D ~sol:C sol:'.':C bar ...
	sol:N sol:N sol:'.':C sol:'.':C sol:C sol:'.':C bar ...
	sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':C sol:'.':D sol:D ~sol:C sol:'.':C bar ...
	sol:N sol:N sol:'.':C sol:'.':C sol:C sol:'.':C bar ...
	sol:'.':C sol:'.':C sol:D sol:D S:D sol:D S:D sol:C' S:C sol:C bar ];

PONT2 = [ Note('') ...
	~fa:C S:C +do:C ~si:C S:C sol:C S:C la:C bar ...
	~la:N +do:C +do:C ~si:C si:C sol:C ~mi:C bar ...
	~mi:N +do:C ~si:C S:C sol:C S:C la:C bar ...
	~la:N +mi:C +mi:'.':C +mi:C +mi:C ~+re:C ~+do:C bar ...
	S:N +do:C ~si:C S:C sol:C S:C la:C bar ...
	~la:N +do:C +do:C ~si:C si:C sol:C ~mi:C bar ...
	~mi:N +do:C ~si:C S:C sol:C S:C la:C bar ...
	~la:N +mi:C +mi:'.':C +mi:C +mi:C ~+re:C ~+do:C bar ...
	~+do:B' ~+do:C S:C bar ...
	Note('+') S:N mi:C mi:'.':C mi:C mi:C sol:C ~do:C bar ...
	~do:B S:B bar ...
	S:N +do:C +do:'.':C +do:C +do:C ~si:C ~la:C bar ...
	~la:C ~sol:D ~fa:D ~fa:B S:N bar ...
	S:C +do:'.':C +do:C ~la:'.':C +do:C ~la:C ~+do:N bar ...
	S:R bar ...
	S:C +do:'.':C +do:C ~la:'.':C +do:C ~la:C ~+do:N bar ];
	
CODA = [ Note('+') ...
	[ S:R bar ...
	S:C +do:'.':C +do:C ~la:'.':C +do:C ~la:C ~+do:N bar ]*3 ...
	S:R bar ...
	S:R bar ];

CHANT = [ ...
	MARKER_INTRO HOHOHO*2 S:B bar ...
	MARKER_A HAHA*2 ...
	MARKER_B COUPLET ...
	MARKER_C REFRAIN HOHOHO*2 S:B bar ...
	MARKER_D HAHA ...
	MARKER_E COUPLET ...
	MARKER_F REFRAIN HOHOHO*2 S:B bar ...
	MARKER_G HAHA*2 ...
	MARKER_H PONT1 ...
	MARKER_I PONT2 ...
	MARKER_J REFRAIN S:B bar ...
	MARKER_K CODA HAHA ...
	MARKER_END ];
	
%% CACOFONIX

cacofonix( 'BadRomance', 'Tempo', 120, MAIN, 'Flute', CHANT );

