
%
% Dark World
%
% Compositor: Koji Kondo
% From: The Legend of Zelda: A Link to the Past
%

clc

NoteInit_fr

[siN, si] = deal(si, siB);
[miN, mi] = deal(mi, miB);
[laN, la] = deal(la, laB);

markA = Note( 'Marker', 'A' );
markB = Note( 'Marker', 'B' );
markC = Note( 'Marker', 'B' );

%% Main Droite

MD = [ ...
	S:C (mi+sol).*[C C D D C] fa+laN:[C N] bar ...
	S:C (sol+si).*[C C D D C] laN++do:[C N] bar ...
	S:C (mi+sol).*[C C D D C] fa+laN:[C N] bar ...
	S:C (sol+si).*[C C D D C] laN++do:[C C] do:C bar ...
	markA sol:B ~sol:C do:C sol:C +do:C bar ...
	laN:D si:D laN:[C B C'] fa:D bar ...
	sol:N do:[B C] fa:C bar ...
	re:D mi:D re:[C B C'] -si:D bar ...
	do:B' S:C +do:D +sol:D bar ...
	+re:B' S:C do:C bar ...
	sol:[B C] do:C sol:C +do:C bar ...
	laN:D si:D laN:[C B C'] fa:D bar ...
	sol:N do:[B C] fa:C bar ...
	re:D mi:D re:[C B C'] re:D bar ...
	do:B' [+fa +mi +re +do].*D bar ...
	+re:B' S:C sol:D laN:D bar ...
	markB si:B' sol:C si:C bar ...
	laN:D sol:D fa:[C B] S:C mi:D fa:D bar ...
	sol:B' do:C sol:C bar ...
	fa:D mi:D re:[C B] S:C sol:D laN:D bar ...
	si:B' sol:C si:C bar ...
	laN:D si:D +do:[C B'] bar ...
	si:B' laN:C si:C bar ...
	laN:D solD:D laN:[C B'] bar ...
	sol:B do+miN:C do+miN:[C N] bar ...
	S:C (re+fa).*[C C D D] (do+miN).*[C C+N] bar ...
	markC [+do sol fa sol].*D ~sol:B +do:N bar ...
	[si sol fa sol].*D ~sol:B' bar ...
	[si fa mi fa].*D ~fa:B si:N bar ...
	[laN mi re mi].*D ~mi:B' bar ...
	[sol re reB re].*D ~re:B sol:N bar ...
	[+do sol fa sol].*D ~sol:B +do:N bar ...
	+re:R bar ...
	~+re:R bar ];

%% Main Gauche

RIFF1 = [ V:N V:N V:N' V:C bar ];
RIFF2 = [ V-1:C (V-2).*[C C D D C] (V-3):[C N] bar ];
RIFF3 = [ (V-1:R) / ( (V-2).*[C N C C N C] ) bar ];
RIFF4 = [ V:N S:C V:N V:C V:N bar ];

MG = [ Note('-') ...
	( do*RIFF1 )*4 ...
	markA [do mi+sol mi+sol]*RIFF2 ...
	[-fa fa+laN fa+laN]*RIFF2 ...
	[-la mi+sol mi+sol]*RIFF2 ...
	[-si re+fa re+fa]*RIFF2 ...
	[do mi+sol fa+laN]*RIFF2 ...
	[do sol+si laN++do]*RIFF2 ...
	[do mi+sol mi+sol]*RIFF2 ...
	[-fa fa+laN fa+laN]*RIFF2 ...
	[-la mi+sol mi+sol]*RIFF2 ...
	[-si re+fa re+fa]*RIFF2 ...
	[do mi+sol fa+laN]*RIFF2 ...
	[do sol+si laN++do]*RIFF2 ...
	markC [sol+si mi]*RIFF3 ...
	[laN++do fa]*RIFF3 ...
	[+do la]*RIFF3 ...
	[+re si]*RIFF3 ...
	[sol+si mi]*RIFF3 ...
	[laN++do fa]*RIFF3 ...
	[si++reB miN]*RIFF3 ...
	[faD+la re]*RIFF3 ...
	sol:C (si+re).*[C C D D] sol.*[C N C] bar ...
	sol.*[C N C C N C] bar ...
	markC (+do++mi++sol)*RIFF4 ...
	(sol+si++re)*RIFF4 ...
	(faD+laN++do)*RIFF4 ...
	(fa+la++do)*RIFF4 ...
	(miN+solD+siN)*RIFF4 ...
	(mi+sol+si)*RIFF4 ...
	(re+faD++do)*RIFF4 ...
	sol++do:N S:C sol++do:N sol+siN:C sol+siN:N bar ];
	

%% Cacofonix

cacofonix( 'DarkWorld', 'Tempo', 138, (MD/MG)*2 );
	
	
