
%
% Für Elise
%
% Compositor: Ludwig van Beethoven
%

%#ok<*BDSCA>
clc

NoteInit

Note.setNbCharByQuater( 48 );

N32 = Note( 1/8 );
N64 = Note( 1/16 );
N24 = Note( 1/6 );

Cresc1 = Note( 'crescendo', N8', 'mf' );
Cresc2 = Note( 'crescendo', N4', 'mf' );
Decresc = Note( 'decrescendo', N8', 'pp' );

SustainON = Note( 'sustain', 'on' );
SustainOFF = Note( 'sustain', 'off' );

tempo = 70;
TEMPO = Note( 'tempo', tempo );
RALL = Note( 'rall', N4', tempo-15 );
RALL2 = Note( 'rall', N4', tempo-20 );

MARK_A = Note( 'marker', 'A' );
MARK_B = Note( 'marker', 'B' );
MARK_C = Note( 'marker', 'C' );
MARK_D = Note( 'marker', 'D' );
MARK_E = Note( 'marker', 'E' );
MARK_F = Note( 'marker', 'F' );

%% RIGHT HAND

RHAna = [ TEMPO Note( [3 8] ) Note( '+' ) DynPP E:N16 ~Ds:N16 bar ];
RHA = [ MARK_A DynPP ...
	~[ [ Cresc1 ~E Ds E Decresc -B D C ].*N16 bar ...
	-A:N8 ] R:N16 ~[ [ -C -E -A ].*N16 bar ...
	-B:N8 ] R:N16 ~[ [ -E -Gs -B ].*N16 bar ...
	C:N8 ]  R:N16 ~[ [ -E E Ds ].*N16 bar ...
	[ Cresc1 E Ds E Decresc -B D C ] .* N16 bar ...
	-A:N8 ] R:N16 ~[ [ -C -E -A ].*N16 bar ...
	-B:N8 ] R:N16 ~[ -E C -B ].*N16 bar ];
RHA1 = [ ~-A:N4  ~[ E:N16 Ds:N16 ] bar ];
RHA2 = [ ~-A:N8  R:N16 Cresc1 ~[ -B:N16 C:N16 D:N16 ] bar ];

RHB = [ MARK_B DynMF ...
	~E:N8' ~[ [ -G F E ].*N16 bar ...
	D:N8' ] ~[ [ -F E D ].*N16 bar ...
	C:N8' ] ~[ [ -E D C ].*N16 bar ...
	-B:N8 ] R:N16 -E:N16 ~E:N16 R:N16 bar ...
	R:N16 E:N16 ~+E:N16 RALL R:[N16 N16] Ds:N16 bar ...
	~E:N16 R:[N16 N16] Decresc TEMPO ~[ Ds:N16 E:N16 Ds:N16 bar ...
	[ E Ds E -B D C ].*N16 bar ...
	-A:N8 ] R:N16 ~[ [ -C -E -A ].*N16 bar ...
	-B:N8 ] R:N16 ~[ [ -E -Gs -B ].*N16 bar ...
	C:N8 ] R:N16 ~[ [ Cresc2 -E E Ds ].*N16 bar ...
	[ E Ds E Decresc -B D C ].*N16 bar ...
	-A:N8 ] R:N16 ~[ [ -C -E -A ].*N16 bar ...
	-B:N8 ] R:N16 ~[ -E C -B ].*N16 bar ...
	];
RHB1 = [ ~-A:N8 R:N16 Cresc1 ~[ -B C D ].*N16 bar ];
RHB2 = [ ~-A:N8 R:N16 Cresc1 [ -E+C -F+C -E+-G+C ] .* (R:'.':N16) bar ];

RHC = [ MARK_C DynMF ...
	~[ -F:N16 -A:N16 C:N8 F:N16' E:N32 bar ...
	E:N8 D:N8 ] ~[ Bf:N16' A:N32 bar ...
	[ A G F E D C ] .* N16 bar ...
	-Bf:N8 -A:N8 ] ~[ -Bf:N16 [ -A -G -A -Bf ].*N64 bar ...
	C:N4 ] ~[ D:N16 Ds:N16 bar ...
	E:N8' ] ~[ E:N16 F:N16 -A:N16 ] bar ...
	~[ C:N4 D:N16' -B:N32 ] bar ...
	DynP [ ~C G ~[ -G G -A G -B G C G D G ] ].*N32 bar ...
	[ ~E ~[ G +C B A G F E D G F D ] ].*N32 bar ...
	[ ~C G ~[ -G G -A G -B G C G D G ] ].*N32 bar ...
	[ ~E ~[ G +C B A G F E D G F D ] ].*N32 bar ...
	~[ E F E Ds E -B E Ds E -B E Ds ].*N32 bar ...
	~E:N8' ~[ -B E Ds ].*N16 bar ...
	~E:N8' -B:N16 ~E:N16 R:N16 bar ...
	RALL R:N16 Ds:N16 ~E:N16 R:[N16 N16] DynPP Ds:N16 bar ...
	];

RHD = [ MARK_D Note( '+' ) TEMPO DynPP ...
	[ Cresc1 E Ds E Decresc -B D C ].*~N16 bar ...
	~-A:N8 R:N16 ~[ -C -E -A ].*N16 bar ...
	~-B:N8 R:N16 ~[ -E -Gs -B ].*N16 bar ...
	~C:N8 R:N16 ~[ Cresc2 -E E Ds ].*N16 bar ...
	[ E Ds E Decresc -B D C ].*~N16 bar ...
	~-A:N8 R:N16 ~[ -C -E -A ].*N16 bar ...
	~-B:N8 R:N16 ~[ -E C -B ].*N16 bar ...
	~-A:N8' Cresc1 [ -B C D ].*N16 bar ...
	E:N8' ~[ -G F E ].*N16 bar ...
	~D:N8' ~[ -F E D ].*N16 bar ...
	~C:N8' ~[ -E D C ].*N16 bar ...
	~-B:N8 DynP R:N16 -E:N16 ~E:N16 R:N16 bar ...
	R:N16 E:N16 ~+E:N16 R:[N16 N16] Ds:N16 bar ...
	~E:N16 R:N16 R:N16 ~[ DynPP Ds E Ds ].*N16 bar ...
	[ Cresc1 E Ds E Decresc -B D C ].*~N16 bar ...
	~-A:N8 R:N16 ~[ -C -E -A ].*N16 bar ...
	~-B:N8 R:N16 ~[ -E -Gs -B ].*N16 bar ...
	~C:N8 R:N16 Cresc2 ~[ -E E Ds ].*N16 bar ...
	[ E Ds E Decresc -B D C ].*~N16 bar ...
	~-A:N8 R:N16 ~[ -C -E -A ].*N16 bar ...
	~-B:N8 R:N16 ~[ -E C -B ].*N16 bar ...
	];

RHE = [ MARK_E Note( '+' ) DynP ...
	~-A:N8 R:[N8 N8] bar ...
	[ -E -G -Bf Cs ]:'>':N4' bar ...
	~[ -F -A D ]:'>':N4 Cs+E:N16 ~D+F:N16 bar ...
	-Gs+D+F:'>':N4 -Gs+D+F:N8 bar ...
	~-A+C+E:N4' bar ...
	-F+D:N4 ~[ -E+C:N16 -D+-B:N16 bar ...
	-C+-Fs+-A:N4 ] -C+-A:N8 bar ...
	~[ -C+-A:N8 -E+C:N8 -D+-B:N8 bar ...
	-C+-A:N4' ] DynP bar ...
	[ -E -G -Bf Cs ]:'>':N4' bar ...
	~-F+-A+D:N4 Cs+E:N16 ~D+F:N16 bar ...
	D+F:N4 D+F:N8 bar ...
	D+F:N4' bar ...
	~[ -G+Ef:N4 -F+D:N16 -Ef+C:N16 bar ...
	-D+-F+-Bf:N4 ] -D+-F+-A:N8 bar ...
	~-D+-F+-Gs:N4 -D+-F+-Gs:N8 bar ...
	DynP ~-C+-E+-A:N4 R:N8 bar ...
	DynPP -D+-E+-B:'.':N8 R:[N8 N8] bar ...
	Note( 'crescendo', [ N4' N4' N4 ], 'mp' ) ...
	~[ --A -C -E -A C E D C -B ].*N24 bar ...
	~[ -A C E A +C +E +D +C B ].*N24 bar ...
	~[ A +C +E +A ++C ++E ++D ++C +B ].*N24 bar ...
	~[ +Bf +A +Gs +G +Fs +F +E +Ds +D ].*N24 bar ...
	~[ +Cs +C B Bf A Gs G Fs F ].*N24 bar ...
	DynPP RALL2 ~[ E Ds E -B D C ].*N16 bar ...
	];

RHF = [ MARK_F Note( '+' ) TEMPO DynPP ...
	~-A:N8 R:N16 ~[ -C -E -A ].*N16 bar ...
	~-B:N8 R:N16 ~[ -E -Gs -B ].*N16 bar ...
	~C:N8 R:N16 ~[ [ -E E Ds ].*N16 bar ...
	[ Cresc1 E Ds E Decresc -B D C ].*N16 bar ...
	-A:N8 ] R:N16 ~[ -C -E -A ].*N16 bar ...
	~-B:N8 R:N16 ~[ -E C -B ].*N16 bar ...
	~-A:N8 R:N16 Cresc1 ~[ -B C D ].*N16 bar ...
	~E:N8' ~[ -G F E ].*N16 bar ...
	~D:N8' ~[ -F E D ].*N16 bar ...
	~C:N8' ~[ -E D C ].*N16 bar ...
	~-B:N8 DynP R:N16 -E:N16 ~E:N16 R:N16 bar ...
	R:N16 E:N16 ~+E:N16 R:[N16 N16] Ds:N16 bar ...
	~E:N16 R:[N16 N16] DynPP ~[ [ Ds E Ds ].*N16 bar ...
	[ E Ds E -B D C ].*N16 bar ...
	-A:N8 ] R:N16 ~[ -C -E -A ].*N16 bar ...
	~-B:N8 R:N16 ~[ -E -Gs -B ].*N16 bar ...
	~C:N8 R:N16 Cresc1 ~[ [ -E E Ds ].*N16 bar ...
	[ E Ds E Decresc -B D C ].*~N16 bar ...
	-A:N8 ] R:N16 ~[ -C -E -A ].*N16 bar ...
	RALL2 ~-B:N8 R:N16 ~[ -E C -B ].*N16 bar ...
	-A:'-':N4' bar ...
	];

%% LEFT HAND

RIFF = [ SustainON ~[ (V-1):N16 (V-2):N16 (V-3):N16 ] SustainOFF R:[N16 N8] bar ];

LHAna = [ Note( '-' ) DynPP R:N8 bar ];
LHA = [ MARK_A ...
	R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	[ -A E A ] * RIFF ...
	R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	];
LHA1 = [ -A E A ] * RIFF;
LHA2 = [ -A E A ] * RIFF;

LHB = [ MARK_B DynMF ...
	[ -C G +C ] * RIFF ...
	[ -G G B ] * RIFF ...
	[ -A E A ] * RIFF ...
	SustainON -E:'.':N16 E:N16 ~+E:N16 R:[N16 N16] +E:N16 bar ...
	~++E:N16 R:[N16 N16] SustainOFF ++Ds:N16 ~++E:N16 R:N16 bar ...
	R:N16 ++Ds:N16 ~++E:N16 R:N16 R:N8 bar ...
	DynPP R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	[ -A E A ] * RIFF ...
	R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	];
LHB1 = [ -A E A ] * RIFF;
LHB2 = [ SustainON ~[ -A E A ].*N16 SustainOFF Cresc1 Bf++C:'.':N16 ~A++C:'.':N16 ~G++C:'.':N16 bar ];

LHC = [ MARK_C Note( '-' ) ...
	~[ F A +C A +C A ].*N16 bar ...
	~[ F Bf +D Bf +D Bf ].*N16 bar ...
	~[ F +E F+G+Bf +E F+G+Bf +E ].*N16 bar ...
	~[ F A +C A +C A ].*N16 bar ...
	~[ F A +C A +C A ].*N16 bar ...
	~[ E A +C A D++D F ].*N16 bar ...
	~[ G +E G +E G +F ].*N16 bar ...
	DynP +C++E:N8 R:N16 +F++G:'.':N16 +E+G:'.':N16 +D++F++G:'.':N16 bar ...
	+C++E++G:N8 ~[ F+A:N8 G+B:N8 bar ...
	+C:N8 ] R:N16 +F++G:'.':N16 +E+G:'.':N16 +D++F++G:'.':N16 bar ...
	+C++E++G:N8 F+A:N8 ~G+B:N8 bar ...
	~Gs+B:N8 R:N8 R:N8 bar ...
	R:N4' bar ...
	R:N4 R:N16 ++Ds:N16 bar ...
	~++E:N16 R:N16 R:N16 ++Ds:N16 ~++E:N16 DynPP R:N16 bar ];

LHD = [ MARK_D Note( '-' ) DynPP ...
	R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	[ -A E A ] * RIFF ...
	R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	[ -A E A ] * RIFF ...
	DynMF [ C G +C ] * RIFF ...
	[ -G G B ] * RIFF ...
	[ -A E A ] * RIFF ...
	DynP SustainON -E:'.':N16 E:N16 ~+E:N16 R:[N16 N16] +E:N16 bar ...
	~++E:N16 R:[N16 N16] SustainOFF ++Ds:N16 ~++E:N16 R:N16 bar ...
	R:N16 ++Ds:N16 ~++E:N16 R:[N16 N8] bar ...
	DynPP R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	[ -A E A ] * RIFF ...
	R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	];

LHE = [ MARK_E Note( '--' ) DynP ...
	SustainON ( A:'.':N16 )*6 bar ...
	SustainON ( A:'.':N16 )*6 bar ...
	SustainON ( A:'.':N16 )*6 bar ...
	SustainON ( A:'.':N16 )*6 bar ...
	SustainON ( A:'.':N16 )*6 bar ...
	SustainON ( D+A:'.':N16 )*6 bar ...
	SustainON ( Ds+A:'.':N16 )*6 bar ...
	SustainON ( E+A:'.':N16 )*4 SustainON ( E+Gs:'.':N16 )*2 bar ...
	DynP SustainON -A+A:N16 ( A:'.':N16 )*5 bar ...
	SustainON ( A:'.':N16 )*6 bar ...
	SustainON ( A:'.':N16 )*6 bar ...
	SustainON ( A:'.':N16 )*6 bar ...
	SustainON ( Bf:'.':N16 )*6 bar ...
	SustainON ( Bf:'.':N16 )*6 bar ...
	SustainON ( Bf:'.':N16 )*6 bar ...
	SustainON ( B:'.':N16 )*6 bar ...
	Note( '-' ) SustainON C:N4 SustainOFF R:N8 bar ...
	DynPP E+Gs:'.':N8 R:N8 R:N8 bar ...
	Note( 'crescendo', [ N4' N4' N4 ], 'mp' ) ...
	SustainON --A:N8 R:N8 A++C++E:'.':N8 bar ...
	A++C++E:'.':N8 R:N8 A++C++E:'.':N8 bar ...
	A++C++E:'.':N8 R:N8 A++C++E:'.':N8 bar ...
	A++C++E:N8 SustainOFF R:N8 R:N8 bar ...
	R:N4' bar ...
	R:N4' bar ...
	];
	
LHF = [ MARK_F Note( '-' ) DynPP ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	[ -A E A ] * RIFF ...
	R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	[ -A E A ] * RIFF ...
	DynMF ...
	[ C G +C ] * RIFF ...
	[ -G G B ] * RIFF ...
	[ -A E A ] * RIFF ...
	DynP SustainON -E:'.':N16 E:N16 ~+E:N16 R:[N16 N16] +E:N16 bar ...
	~++E:N16 R:[N16 N16] SustainOFF ++Ds:N16 ~++E:N16 R:N16 bar ...
	R:N16 ++Ds:N16 ++E:N16 R:[N16 N8] bar ...
	DynPP R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	[ -A E A ] * RIFF ...
	R:N4' bar ...
	[ -A E A ] * RIFF ...
	[ -E E Gs ] * RIFF ...
	--A+-A:'-':N4' bar ...
	];
	
%% CACOFONIX

cacofonix( 'FurElise.mid', 'Velocity', linspace( 25, 100, 8 ), 'Piano', ...
	[ RHAna RHA RHA1 RHA RHA2 RHB RHB1 RHB RHB2 RHC RHD RHE RHF] / ...
	[ LHAna LHA LHA1 LHA LHA2 LHB LHB1 LHB LHB2 LHC LHD LHE LHF] );
