NoteInit

COUPLET = Note( 'Marker', 'COUPLET' );

RYHTMIC = [ ...
	R:N8 G:N8 A:N8 C++C:N8 bar ...
	~C++C:N2 R:N8 G:N8 A:N8 D++D:N8 bar ...
	~D++D:N2 R:N8 D++D:N8 E++E:N8 F++F:N8 bar ...
	~F++F:[N2 N8] F:N8 G:N8 C++C:N8 bar ...
	~C++C:N2 ];

RIFF_CHOEUR = [ V-0:N8 bar ~V-0:[N2 N4'] ];
CHOEUR = [ ...
	C*CM*RIFF_CHOEUR ...
	D*CM*RIFF_CHOEUR ...
	F*CM*RIFF_CHOEUR ...
	C*CM*RIFF_CHOEUR ];
CHOEUR2 = [ ...
	(-G+C+E)*RIFF_CHOEUR ...
	(-Fs+-A+C+D)*RIFF_CHOEUR ...
	(-A+C)*RIFF_CHOEUR ...
	(-E+-G+C)*RIFF_CHOEUR ];

PIANO_L = [ Note('--') RYHTMIC COUPLET RYHTMIC ~C++C:N2 bar ];
PIANO_R = [ R:N4' CHOEUR2*2 ~-E+-G+C:N8 bar ];

LYRIC = [ ~COUPLET ...
	R:N8 C:N8 E:N8 G:N8 bar ...
	A:N8 A:N8 G:N4 E:N4 D:N8 C:N8 bar ...
	C:N8 D:N4 -A:N4 -G:N8 -A:N8 C:N8 bar ...
	~C:N4 G:N4 E:N4 D:N8 C:N8 bar ...
	R:N bar ];

BASS = [ Note('-') ~COUPLET [ RYHTMIC ~C++C:N2 ] / [R:N4' CHOEUR R:N8 ] bar ];

CHOEUR = [ ~COUPLET R:N4' ...
	C*RIFF_CHOEUR ...
	D*RIFF_CHOEUR ...
	F*RIFF_CHOEUR ...
	C*CM:N8 bar ...
	~C*CM:N8 G:N8 A:N8 +C:N4 R:N4' bar ];

PERCU1 = [ R:N4 8*[ R R R R bar R R R R V R V V R R R R ].*N16 R R R R bar ];
PERCU2 = [ R:N4 8*[ R R V V bar V R V R R R R R R R V R ].*N16 R R R R bar ];
TAMBOU = [ R:N4 8*[ V R R R bar R R R R R R R R R R R R ].*N16 R R R R bar ];

cacofonix( 'F@#getYou_CeeLo', 'Tempo', 130, ...
	'Honky-tonk Piano', PIANO_L/PIANO_R, ...
	'Solo Synth Vox', LYRIC, ...
	'Voice Oohs', CHOEUR, ...
	'Acoustic Bass', BASS, ...
	'Hi Bongo', PERCU1, ...
	'Low Bongo', PERCU2, ...
	'Tambourine', TAMBOU );