
%
% Comptine d'un Autre Eté: L'Après Midi
%
% Compositor: Yann Tiersen
% From: Le Fabuleux Destin d'Amélie Poulain
%

%#ok<*BDSCA>
clc

NoteInit_fr

[fa,faD] = deal( faD, fa );

Tempo = Note( 'Tempo', 100 );

Cresc01 = Note( 'Cresc', R, 'mp' );
Decre01 = Note( 'Decresc', R, 'p' );

Cresc11 = Note( 'Cresc', N, 'f' );
Decre11 = Note( 'Decresc', [N B], 'mf', N );
Decre12 = Note( 'Decresc', R, 'p' );

Cresc21 = Note( 'Cresc', R, 'mp' );
Decre21 = Note( 'Decresc', R, 'p' );
Cresc22 = Note( 'Cresc', R, 'f' );
Decre22 = Note( 'Decresc', R, 'mf' );

Cresc31 = Note( 'Cresc', R, 'f' );
Decre31 = Note( 'Decresc', R, 'mf' );
Decre32 = Note( 'Decresc', B, 'mf' );
Tempo31 = Note( 'Rall', B, 50 );

Cresc41 = Note( 'Cresc', R, 'mp' );
Decre41 = Note( 'Decresc', R, 'p' );

Cresc51 = Note( 'Cresc', R, 'mp' );
Decre51 = Note( 'Decresc', R, 'p' );
Cresc52 = Note( 'Cresc', R, 'f' );
Decre52 = Note( 'Decresc', R, 'mf' );

Cresc61 = Note( 'Cresc', R, 'mf' );
Decre61 = Note( 'Decresc', R, 'p' );
Decre62 = Note( 'Decresc', R, 'pp' );
Tempo61 = Note( 'Rall', R, 15 );

PIANOMD = [ Tempo ...
	[ S:R bar ]*4 ...
	DynMF S:C ~[ sol:D fa:D sol:C si:D +do:D si:B ] bar ...
	Cresc11 Decre11 S:C ~[ fa:D sol:D fa:C sol:D la:D sol:B ] bar ...
	Cresc11 Decre11 S:C ~[ fa:D mi:D fa:C si:D +do:D si:B ] bar ...
	Decre12 S:C ~[ fa:D mi:D fa:B' ] bar ...
	DynMF S:C ~[ sol:D fa:D sol:C si:D +do:D si:B ] bar ...
	Cresc11 Decre11 S:C ~[ fa:D sol:D fa:C sol:D la:D sol:B ] bar ...
	Cresc11 Decre11 S:C ~[ fa:D mi:D fa:C si:D +do:D si:B ] bar ...
	Decre12 S:C ~[ fa:D mi:D fa:B' ] bar ...
	DynP ~[ +mi:N' si:C ~si:B ] bar ...
	Cresc21 ~[ +re:N' si:C ~si:B ] bar ...
	~[ +fa:N' si:C ~si:B ] bar ...
	Decre21 ~[ +fa:N' la:C ~la:B ] bar ...
	DynMF ~[ si++sol:N' sol++mi:C ~sol++mi:B ] bar ...
	Cresc22 ~[ si++sol:N' sol++re:C ~sol++re:B ] bar ...
	~[ si++fa:N' fa++re:C ~fa++re:B ] bar ...
	Decre22 ~[ la++fa:N' fa++re:C ~fa++re:B ] bar ...
	DynMF si:'>':D +mi:D +si:D si:D +mi:D +si:D si:D +mi:D +si:D si:D +mi:D +si:D ~[ si:'>':D +mi:D +do:'>':D +mi:D bar ...
	Cresc31 si:'>':D ] +re:D +si:D si:D +re:D +si:D si:D +re:D +si:D si:D +re:D +si:D ~[ si:'>':D +re:D la:'>':D +re:D bar ...
	fa:'>':D ] si:D +fa:D fa:D si:D +fa:D fa:D si:D +fa:D fa:D si:D +fa:D ~[ fa:'>':D si:D sol:'>':D si:D bar ...
	Decre31 la:'>':D ] +re:D +la:D la:D +re:D +la:D la:D +re:D +la:D la:D +re:D +la:D ~[ la:'>':D +re:D sol:'>':D +re:D bar ...
	DynMF si:'>':D ] +mi:D +si:D si:D +mi:D +si:D si:D +mi:D +si:D si:D +mi:D +si:D ~[ si:'>':D +mi:D +do:'>':D +mi:D bar ...
	Cresc31 si:'>':D ] +re:D +si:D si:D +re:D +si:D si:D +re:D +si:D si:D +re:D +si:D ~[ si:'>':D +re:D la:'>':D +re:D bar ...
	fa:'>':D ] si:D +fa:D fa:D si:D +fa:D fa:D si:D +fa:D fa:D si:D +fa:D ~[ fa:'>':D si:D sol:'>':D si:D bar ...
	Decre32 la:'>':D ] +re:D +la:D la:D +re:D +la:D la:D +re:D Tempo31 +la:D la:D +re:D +la:D la:D +re:D +la:C bar ...
	Tempo Note('+') DynP S:C ~[ sol:D fa:D sol:C si:D +do:D si:B ] bar ...
	Cresc41 S:C ~[ fa:D sol:D fa:C sol:D la:D sol:B ] bar ...
	S:C ~[ fa:D mi:D fa:C si:D +do:D si:B ] bar ...
	Decre41 S:C ~[ fa:D mi:D fa:B' ] bar ...
	DynP S:C ~[ sol:D fa:D sol:C si:D +do:D si:B ] bar ...
	Cresc41 S:C ~[ fa:D sol:D fa:C sol:D la:D sol:B ] bar ...
	S:C ~[ fa:D mi:D fa:C si:D +do:D si:B ] bar ...
	Decre41 S:C ~[ fa:D mi:D fa:B' ] bar ...
	DynP ~[ +mi:N' si:C ~si:B ] bar ...
	Cresc51 ~[ +re:N' si:C ~si:B ] bar ...
	~[ +fa:N' si:C ~si:B ] bar ...
	Decre51 ~[ +fa:N' la:C ~la:B ] bar ...
	DynMF ~[ si++sol:N' sol++mi:C ~sol++mi:B ] bar ...
	Cresc52 ~[ si++sol:N' sol++re:C ~sol++re:B ] bar ...
	~[ si++fa:N' fa++re:C ~fa++re:B ] bar ...
	Decre52 ~[ la++fa:N' fa++re:C ~fa++re:B ] bar ...
	DynP si:D +mi:D +si:D si:D +mi:D +si:D si:D +mi:D +si:D si:D +mi:D +si:D ~[ si:'>':D +mi:D +do:'>':D +mi:D bar ...
	Cresc61 si:'>':D ] +re:D +si:D si:D +re:D +si:D si:D +re:D +si:D si:D +re:D +si:D ~[ si:'>':D +re:D la:'>':D +re:D bar ...
	fa:'>':D ] si:D +fa:D fa:D si:D +fa:D fa:D si:D +fa:D fa:D si:D +fa:D ~[ fa:'>':D si:D sol:'>':D si:D bar ...
	Decre61 la:'>':D ] +re:D +la:D la:D +re:D +la:D la:D +re:D +la:D la:D +re:D +la:D ~[ la:'>':D +re:D sol:'>':D +re:D bar ...
	si:'>':D ] +mi:D +si:D si:D +mi:D +si:D si:D +mi:D +si:D si:D +mi:D +si:D ~[ si:'>':D +mi:D +do:'>':D +mi:D bar ...
	Cresc61 si:'>':D ] +re:D +si:D si:D +re:D +si:D si:D +re:D +si:D si:D +re:D +si:D ~[ si:'>':D +re:D la:'>':D +re:D bar ...
	fa:'>':D ] si:D +fa:D fa:D si:D +fa:D fa:D si:D +fa:D fa:D si:D +fa:D ~[ fa:'>':D si:D sol:'>':D si:D bar ...
	Decre62 Tempo61 la:'>':D ] +re:D +la:D la:D +re:D +la:D la:D +re:D +la:D la:D +re:D +la:D la:D +re:D +la:D +sol:D bar ...
	DynPP sol+si++mi:N Tempo S:B' bar ...
	];

RIFF = ([ V-1:N V-2:N ]*2) / ([ V-3:C V-4:C ]*4);
PIANOMG = [ Note('-')  ...
	DynP [ mi sol +mi si ]*RIFF bar ...
	Cresc01 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre01 [ re fa +re la ]*RIFF bar ...
	DynMF [ mi sol +mi si ]*RIFF bar ...
	Cresc11 Decre11 [ re sol +re si ]*RIFF bar ...
	Cresc11 Decre11 [ re fa +re si ]*RIFF bar ...
	Decre12 [ re fa +re la ]*RIFF bar ...
	DynMF [ mi sol +mi si ]*RIFF bar ...
	Cresc11 Decre11 [ re sol +re si ]*RIFF bar ...
	Cresc11 Decre11 [ re fa +re si ]*RIFF bar ...
	Decre12 [ re fa +re la ]*RIFF bar ...
	DynP [ mi sol +mi si ]*RIFF bar ...
	Cresc21 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre21 [ re fa +re la ]*RIFF bar ...
	DynMF [ mi sol +mi si ]*RIFF bar ...
	Cresc22 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre22 [ re fa +re la ]*RIFF bar ...
	DynMF [ mi sol +mi si ]*RIFF bar ...
	Cresc31 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre31 [ re fa +re la ]*RIFF bar ...
	DynMF [ mi sol +mi si ]*RIFF bar ...
	Cresc31 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre32 [ re fa +re la ]*RIFF bar ...
	DynP [ mi sol +mi si ]*RIFF bar ...
	Cresc41 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre41 [ re fa +re la ]*RIFF bar ...
	DynP [ mi sol +mi si ]*RIFF bar ...
	Cresc41 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre41 [ re fa +re la ]*RIFF bar ...
	DynP [ mi sol +mi si ]*RIFF bar ...
	Cresc51 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre51 [ re fa +re la ]*RIFF bar ...
	DynMF [ mi sol +mi si ]*RIFF bar ...
	Cresc52 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre52 [ re fa +re la ]*RIFF bar ...
	DynP [ mi sol +mi si ]*RIFF bar ...
	Cresc61 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre61 [ re fa +re la ]*RIFF bar ...
	[ mi sol +mi si ]*RIFF bar ...
	Cresc61 [ re sol +re si ]*RIFF bar ...
	[ re fa +re si ]*RIFF bar ...
	Decre62 [ re:N fa:N re:B ] / [ +re:C la:C +re:C la:C +re:C la:C +re:N ] bar ...
	DynPP mi+si++mi:R bar ...
	];

cacofonix( 'LApresMidi', 'Velocity', linspace( 25, 100, 8 ), PIANOMD / PIANOMG );
