
%
% Legendary Hero
%
% Compositors: Kenta Nagata, Hajime Wakai, Toru Minegishi, Koji Kondo
% From: The Legend of Zelda: The Wind Waker
%

%#ok<*BDSCA>
clc

NoteInit_fr
DD = Note( 1/8 );
DDD = Note( 1/16 );

Note.setNbCharByQuater(48)

MARKIntro = Note( 'marker', 'Intro' );
MARKA = Note( 'marker', 'A' );
MARKB = Note( 'marker', 'B' );
MARKC = Note( 'marker', 'C' );
MARKD = Note( 'marker', 'D' );
MARKD2 = Note( 'marker', 'D''' );
MARKE = Note( 'marker', 'E' );
MARKF = Note( 'marker', 'F' );
MARKF2 = Note( 'marker', 'F''' );
MARKFIN = Note( 'marker', 'FIN' );

%% Main

P = [ S:R bar ];

MAIN = [ ...
	MARKIntro Note( 'tempo', 60 ) Note([2 4]) S:B bar ...
	S:B bar ...
	Note( 'fermata', B, B' ) S:B bar ...
	MARKA Note( 'tempo', 77 ) Note([4 4]) P*8 ...
	MARKB Note( 'rall', R*5, 40 ) P*5 ...
	MARKC Note( 'tempo', 115 ) P*4 ...
	MARKD P*8 ...
	MARKD2 P*11 Note( 'fermata', R, R' ) P ...
	MARKE Note( 'tempo', 62 ) P*6 ...
	S:B' Note( 'rall', N, 50 ) N bar ...
	S:B' Note( 'accel', [N B], 100 ) N bar ...
	P S:B Note( 'rall', B, 50 ) S:B bar P P P ...
	S:B Note( 'fermata', B, R ) S:B bar ...
	MARKF Note( 'tempo', 80 ) P*8 ...
	MARKF2 P*4 S:B Note( 'rall', B', 50 ) S:B bar S:B' Note( 'fermata', N, B' ) S:N MARKFIN ];
	

%% CLAVECIN

CLAVECIN = [ Note('-') ...
	MARKIntro ~[ la:B bar la:B bar la:B bar ] / [ S:N ~[ [la si +do +re].*DDD +mi:C' bar ...
	+mi:N ] mi:N bar ...
	fa:B bar ] ...
	MARKA ~MARKB ...
	mi:B [mi solD si +mi +solD]:'$':B bar ...
	mi:B [si +re +mi]:'$':B bar ...
	mi:B [mi solD si]:'$':N +re:N bar ...
	[mi solD si]:'$':N +fa:N Note('+') re:C fa:C solD:C si:C bar ...
	+re:B' S:N bar ...
	MARKC Note('-') +mi:N (+mi:T)*3 +mi:N (+mi:T)*3 bar ...
	+re:N (+re:T)*3 +re:N (+re:T)*3 bar ...
	+do:T*2 si:T (+do:T)*3 +do:N (+do:T)*3 bar ...
	la:C solD.*[D D C D D C D D C C] bar ...
	MARKD la:N la:N mi:C' la:D la:D si:D +doD:D +re:D bar ...
	+mi:C' la:D la:D si:D +doD:D +re:D +mi:T*2 [+mi +mi +fa +sol].*T bar ...
	+la:C' [fa fa sol la si].*D +do:T*2 [la la sol fa].*T bar ...
	sol:T*2 fa:T mi:T mi:T re:T mi:N mi:N bar ...
	re:C re:D mi:D fa:C fa:D sol:D la:N mi:C re:C bar ...
	do:C do:D re:D mi:C mi:D fa:D sol:N re:C do:C bar ...
	-si:C -si:D doD:D reD:C reD:D mi:D faD:C faD:D solD:D la:N bar ...
	solD:C la.*[D D C D D C D D N] bar ...
	MARKD2 la:N la:N mi:C' la:D la:D si:D +doD:D +re:D bar ...
	+mi:C' la:D la:D si:D +doD:D +re:D +mi:T*2 [+mi +mi +fa +sol].*T bar ...
	+la:C' [fa fa sol la si].*D +do:N +miB:N bar ...
	+mi:N si:N solD:N mi:N bar ...
	miB:N solB:N la:N +miB:N bar ...
	+mi:N mi:T mi:T mi:T mi:N mi:N bar ...
	miB:N solB:N la:N +miB:N bar ...
	+mi:N mi:T mi:T mi:T mi:N S:N bar ...
	P*4 MARKE Note('-') P ...
	S:N mi+si:'>':B' bar ...
	S:R bar ...
	S:N mi+si++mi:'>':B' bar ...
	P ...
	la+si++mi:'$':B -la++do++fa:'$':B bar ...
	solD+si++mi:R bar ...
	~solD+si++mi:B S:B bar ...
	P P ...
	S:B mi+si++mi:B bar ...
	fa++do++fa:B mi+si++mi:B bar ...
	~mi+si++mi:R bar ...
	~mi+si++mi:B S:B bar ...
	MARKF la++do++mi:'$':B' si++re++sol:'.':C si++re++sol:'.':C bar ...
	la++do++mi:B' sol+si++re:'.':C sol+si++re:'.':C bar ...
	la++do++mi:B' si++re++sol:'.':C si++re++sol:'.':C bar ...
	la++do++mi:B' sol+si++re:'.':C sol+si++re:'.':C bar ...
	fa+la++do:B do+sol++do:B bar ...
	fa+la++do:B sol++do++mi:B bar ...
	fa+la++do:B do+sol++do:B bar ...
	mi+la+si:B mi+solD+si:B bar ...
	MARKF2 la++do++mi:B' si++re++sol:'.':C si++re++sol:'.':C bar ...
	la++do++mi:B' sol+si++re:'.':C sol+si++re:'.':C bar ...
	la++do++mi:B' si++re++sol:'.':C si++re++sol:'.':C bar ...
	la++do++mi:B' sol+si++re:'.':C sol+si++re:'.':C bar ...
	[-fa fa la +do fa la +do +fa].*C bar ...
	[-la mi la +mi +la ++mi].*C ++la:N bar MARKFIN ];

%% FLUTES

FLUTE1 = [ ...
	~MARKA S:C +mi:D +mi:D +mi:N ~+mi:C +mi:D +do:D +re:'.':C si:'.':C bar ...
	la:R bar ...
	S:C +do++mi:D +do++mi:D +mi:[N C] +mi:D la++do:D +re:'.':C si:'.':C bar ...
	la:B' S:N bar ...
	la:C +do:C si:DD +do:DD si:D sol:C mi:B bar ...
	la:C +do:C si:DD +do:DD si:D sol:C +mi:B bar ...
	la:C +do:C si:DD +do:DD si:D sol:C mi:N' re:C bar ...
	mi:R bar ...
	MARKB [re mi fa solD ].*C si:B bar ...
	[re mi fa +re].*C si:B bar ...
	[re mi fa solD fa solD si +re].*C bar ...
	[solD si +re +fa].*C +si:B bar ...
	~+si:B' S:N bar ...
	MARKC ~MARKF S:C +mi:D +mi:D +mi:N ~+mi:C +mi:D +do:D +re:'.':C si:'.':C bar ...
	la:R bar ...
	S:C +do++mi:D +do++mi:D +mi:[N C] +mi:D la++do:D si++re:'.':C sol+si:'.':C bar ...
	la:B' S:N bar ...
	la:C +do:C si:DD +do:DD si:D sol:C mi:B bar ...
	la:C +do:C si:DD +do:DD si:D sol:C +mi:B bar ...
	la:C +do:C si:DD +do:DD si:D sol:C mi:N' re:C bar ...
	mi:R bar ...
	MARKF2 S:C +mi:D +mi:D +mi:N ~+mi:C +mi:D +do:D +re:'.':C si:'.':C bar ...
	la:B' S:N bar ...
	S:C [+do +mi]:D [+do +mi]:D +mi:N ~+mi:C +mi:D +do:D +re:'.':C si:'.':C bar ...
	la:R bar ...
	la:R bar ...
	la:R bar MARKFIN ];

FLUTE2 = [ ...
	~MARKA la:B' sol:'.':C sol:'.':C bar ...
	mi:B' re:'.':C re:'.':C bar ...
	mi:B' sol:'.':C sol:'.':C bar ...
	mi:B' re:'.':C re:'.':C bar ...
	fa:B do:B bar ...
	fa:B do:B bar ...
	fa:B do:N' re:C bar ...
	-si:B -solD:B bar ...
	MARKB S:B' re:N bar ...
	-si:B re:B bar ...
	-si:B re:B bar ...
	fa:B solD:B bar ...
	~solD:B' S:N bar ...
	MARKC ~MARKF la:B' sol:'.':C sol:'.':C bar ...
	mi:B' re:'.':C re:'.':C bar ...
	mi:B' sol:'.':C sol:'.':C bar ...
	mi:B' re:'.':C re:'.':C bar ...
	fa:B do:B bar ...
	fa:B do:B bar ...
	fa:B do:N' re:C bar ...
	-si:B -solD:B bar ...
	MARKF2 la:B' sol:'.':C sol:'.':C bar ...
	mi:B' re:'.':C re:'.':C bar ...
	mi:B' sol:'.':C sol:'.':C bar ...
	mi:B' re:'.':C re:'.':C bar ...
	do:R bar ...
	doD:R bar MARKFIN ];

%% VIOLON

VIOLON1 = [ ...
	~MARKA P*3 Note('-') ...
	S:C si:D +do:D +re:C si:C sol:N' fa:C bar ...
	la:B' do:'.':C sol:'.':C bar ...
	fa:[B C] do:D fa:D sol:'.':C +do:'.':C bar ...
	la:B S:C do:'.':C re:'.':C fa:'.':C bar ...
	mi:B -mi:B bar ...
	MARKB ~MARKC ...
	Note('+0') la:[B T*2] (la:T)*4 bar ...
	la:T*2 sol:T la:[N T*2] (la:T)*4 bar ...
	la:T*2 sol:T la:[N T*2] (la:T)*4 bar ...
	la:C mi:D mi:D mi:C mi:D mi:D mi:C mi:D mi:D mi:C mi:C bar ...
	MARKD la:N mi:[N C'] [la la si +doD +re ].*D bar ...
	Note('+') mi:[B T*2] [mi mi fa sol].*T bar ...
	la:[B T*2] [la la sol fa].*T bar ...
	sol:T*2 fa:T mi:B mi:N bar ...
	re:C re:D mi:D fa:B mi:C re:C bar ...
	do:C do:D re:D mi:B re:C do:C bar ...
	-si:C -si:D doD:D reD:B faD:N bar ...
	mi:C -mi.*[D D C D D C D D C C] bar ...
	MARKD2 -la:N -mi:[N C'] [-la -la -si doD re ].*D bar ...
	mi:[B T*2] [mi mi fa sol].*T bar ...
	la:B' +do:N bar ...
	si:'.':N solD:B mi:N bar ...
	fa:B' la:N bar ...
	solD:'.':N mi:B mi:N bar ...
	fa:B' la:N bar ...
	solD:'.':N mi:B doD:N bar ...
	re:B' fa:N bar ...
	mi:'.':N do:B -la:N bar ...
	-si:B -faD:N -si:N bar ...
	-solD:R bar ...
	MARKE Note('+0') la:B do:N' fa:C bar ...
	mi:B' S:N bar ...
	la:B do:N S:C +do:C bar ...
	si:B' S:N bar ...
	la:B do:N' fa:C bar ...
	mi:B fa:B bar ...
	mi:B [-si mi solD si Note('+') mi fa solD si].*D bar ...
	+mi:[B' D] [+re +do si].*D bar ...
	[+re +do si la +do si la sol si la sol fa la sol fa mi].*D bar ...
	[sol fa mi re fa mi re do mi re do -si re do -si -la].*D bar ...
	Note('+0') [solD fa re -si].*D -solD:C -re:C S:B bar ...
	S:R bar ...
	(+mi:R) / [ si:B la:B ] bar ...
	solD:B' S:N bar ...
	MARKF ];

VIOLON2 = [ ...
	~MARKE Note('--') +fa:R bar ...
	+mi++si:N mi+si:'>':B' bar ...
	+fa:[B C] S:[C N] bar ...
	S:N mi+si++mi:'>':B' bar ...
	P ...
	mi+si:B fa++do:B bar ...
	mi+si:R bar ...
	~mi+si:B S:B bar ...
	P P ...
	S:B mi+si++mi:B bar ...
	fa++do++fa:B mi+si++mi:B bar ...
	~mi+si++mi:R bar ...
	~mi+si++mi:B S:B bar ...
	MARKF ];

%% CONTREBASSE

CONTREBASSE = [ ...
	~MARKC Note('--') la:R bar ...
	sol:R bar ...
	fa:R bar ...
	mi:B' faD:C solD:C bar ...
	MARKD la:R bar ...
	sol:R bar ...
	fa:R bar ...
	+do:R bar ...
	siB:R bar ...
	la:R bar ...
	si:R bar ...
	mi:B' faD:C solD:C bar ...
	MARKD2 la:R bar ...
	sol:R bar ...
	fa:R bar ...
	mi:R bar ...
	[miB la +do +miB +la ++do].*T ++miB:B bar ...
	++mi:N mi:T mi:T mi:T mi:B bar ...
	[miB la +do +miB +la ++do].*T ++miB:B bar ...
	++mi:N mi:T mi:T mi:T mi:B bar ...
	siB:R bar ...
	la:R bar ...
	si:R bar ...
	mi:R bar ...
	MARKE P ...
	S:N mi+si:'>':B' bar ...
	S:R bar ...
	S:N mi+si++mi:'>':B' bar ...
	P ...
	mi+si:B fa++do:B bar ...
	mi+si:R bar ...
	~mi+si:B S:B bar ...
	P P ...
	S:B mi+si++mi:B bar ...
	fa++do++fa:B mi+si++mi:B bar ...
	~mi+si++mi:R bar ...
	~mi+si++mi:B S:B bar ...
	MARKF ~MARKF2 la:B' sol:C sol:C bar ...
	la:B' sol:C sol:C bar ...
	la:B' sol:C sol:C bar ...
	la:R bar ...
	fa:R bar ...
	-la:R bar MARKFIN ];

%% Cacofonix

cacofonix( 'LegendaryHero', 'Velocity', linspace( 50, 126, 8 ), ...
	MAIN, ...
	'Harpsicord', CLAVECIN, ...
	'Piccolo', FLUTE1, ...
	'Piccolo', FLUTE2, ...
	'Violin', VIOLON1, ...
	'Violin', VIOLON2, ...
	'Contrabass', CONTREBASSE );
