
%
% On The Rise (My Eyes)
%
% Compositors: Joss Whedon, Jed Whedon, Zack Whedon, Maurissa Tancharoen
% From: Dr. Horrible's Sing-Along Blog
%

%#ok<*BDSCA>
clc

NoteInit_fr
[fa, faN] = deal(faD, fa);
[do, doN] = deal(doD, do);

DD = Note( 3/4 );

P = [ S:R' bar ];

Note.setNbCharByQuater(12)

%% MAIN

MARK5  = Note('Marker', 'M5');
MARK9  = Note('Marker', 'M9');
MARK13 = Note('Marker', 'M13');
MARK17 = Note('Marker', 'M17');
MARK21 = Note('Marker', 'M21');
MARK26 = Note('Marker', 'M26');
MARK31 = Note('Marker', 'M31');
MARK36 = Note('Marker', 'M36');
MARK41 = Note('Marker', 'M41');
MARK46 = Note('Marker', 'M46');
MARK51 = Note('Marker', 'M51');
MARK56 = Note('Marker', 'M56');
MARK60 = Note('Marker', 'M60');
MARK64 = Note('Marker', 'M64');
MARK68 = Note('Marker', 'M68');
MARK72 = Note('Marker', 'M72');
MARK76 = Note('Marker', 'M76');
MARK81 = Note('Marker', 'M81');
MARK85 = Note('Marker', 'M85');
MARK89 = Note('Marker', 'M89');

MAIN = [ Note([12 8]) P*4 ...
	MARK5 P*4 ...
	MARK9 P*4 ...
	MARK13 P*4 ...
	MARK17 P*4 ...
	MARK21 P*5 ...
	MARK26 P*5 ...
	MARK31 P*5 ...
	MARK36 P*5 ...
	MARK41 P*5 ...
	MARK46 P*5 ...
	MARK51 P*5 ...
	MARK56 P*4 ...
	MARK60 P*4 ...
	MARK64 P*4 ...
	MARK68 P*4 ...
	MARK72 P*4 ...
	MARK76 P*5 ...
	MARK81 P*4 ...
	MARK85 P*4 ...
	MARK89 ];

%% OBOE

OBOE = [ ...
	DynMF ~[ +re:[ B' N' N ] +do:C bar ...
	si:[ B' N' N ] la:C bar ...
	fa:R' bar ...
	fa:R' ] bar ...
	MARK5 ~MARK31 P*2 ...
	DynP la:R' bar ...
	~la:R' bar ...
	re:R' bar ...
	MARK36 ~re:R' bar ...
	la:R' bar ...
	~la:R' bar ...
	re:R' bar ...
	~re:R' bar ...
	MARK41 ~MARK60 P ...
	DynP la:R' bar ...
	~la:R' bar ...
	re:R' bar ...
	MARK64 ~re:R' bar ...
	la:R' bar ...
	~la:R' bar ...
	re:R' bar ...
	MARK68 ~re:R' bar ];

%% STRINGS

STRINGS = [ ...
	~MARK21 P*4 ...
	DynP Note('-') si:R' bar ...
	MARK26 la:R' bar ...
	solD:R' bar ...
	sol:R' bar ...
	~[ fa:R' bar ...
	fa:R' bar ...
	MARK31 fa:R' bar ...
	fa:R' ] bar ...
	~MARK41 Note('') -si+mi+sol:R' bar ...
	-si+re+fa:R' bar ...
	-si+mi+sol:R' bar ...
	-si+re+fa:R' bar ...
	-si+mi+sol:R' bar ...
	MARK46 -si+re+fa:R' bar ...
	~MARK68 P ...
	DynMP -si+mi+sol:R' bar ...
	-si+re+fa:R' bar ...
	-si+mi+sol:R' bar ...
	MARK72 -si+re+fa:R' bar ...
	-si+mi+sol:R' bar ...
	-si+re+fa:R' bar ...
	P MARK76 ];

%% PENNY

PENNY = [ ...
	~MARK31 P*2 ...
	DynMF re:[B' N'] do:N' bar ...
	re:N' S:N re:C mi:N re:C -si:N do:C bar ...
	-la:[B' N'] -fa:N' bar ...
	MARK36 -la:N' S:N -la:C -sol:N -la:C re:N do:C bar ...
	re:[B' N'] do:N' bar ...
	re:N' S:N re:C mi:N re:C -si:N do:C bar ...
	-la:[B' N'] -fa:N' bar ...
	-la:N' -la:N' -la:N' re:N' bar ...
	MARK41 -si:N' -si:N' mi:[N' N] do:C bar ...
	re:N do:C -si:C do:N re:N' S:N' bar ...
	-si:N' -si:N' mi:N' do:N' bar ...
	~[ re:[N' N] do:C -si:B' ] bar ...
	S:N' -si:N' mi:B' bar ...
	MARK46 re:DD do:DD -si:DD do:DD re:N' S:DD do:DD bar ...
	do:[N' DD] re:DD do:[N' DD] re:DD bar ...
	do:[B' N'] S:N mi:C bar ...
	fa:N' mi:N fa:C mi:N' do:N' bar ...
	-si:B' S:N' S:C re:C mi:C bar ...
	MARK51 fa:N' mi:N fa:C mi:N' do:N' bar ...
	-si:B' S:N' S:C re:C mi:C bar ...
	fa:B la:N la:B' bar ...
	~la:B' fa:N mi:N re:N bar ...
	mi:N' -si:N re:[C B'] bar ...
	MARK56 S:N' -fa:N' re:N' do:N' bar ...
	~[ re:[N' N] do:C -si:B' bar ...
	-si:R' ] bar ...
	P ...
	MARK60 P ...
	re:[B' N'] do:N' bar ...
	re:N' S:N re:C mi:N re:C -si:N do:C bar ...
	-la:[B' N'] -fa:N' bar ...
	MARK64 -la:N' S:N -la:C -sol:N -la:C re:N do:C bar ...
	re:[B' N'] do:N' bar ...
	re:N' S:N re:C mi:N re:C -si:N do:C bar ...
	-la:[B' N'] -fa:N' bar ...
	MARK68 -la:N' -la:N' -la:N' re:N' bar ...
	-si:N' -si:N' mi:[N' N] do:C bar ...
	re:N do:C -si:C do:N re:N' S:N' bar ...
	-si:N' -si:N' mi:N' do:N' bar ...
	MARK72 ~[ re:[N' N] do:C -si:[N' N] ] S:C bar ...
	S:N' -si:N' mi:B' bar ...
	re:DD do:DD -si:DD do:DD re:N' S:DD do:DD bar ...
	do:[N' DD] re:DD do:[N' DD] re:DD bar ...
	MARK76 do:[B' N'] S:N DynFF mi:C bar ...
	fa:N' mi:N fa:C mi:N' do:N' bar ...
	-si:B' S:N' S:C re:C mi:C bar ...
	fa:N' mi:N fa:C mi:N' do:N' bar ...
	-si:B' S:N' S:N' bar ...
	MARK81 S:[N' C] re:C mi:C fa:N' la:N' bar ...
	la:[B' B'] bar ...
	faN:N mi:N re:N mi:N' -si:N re:C bar ...
	~re:N' -fa:N' re:N' do:N' bar ...
	MARK85 ~[ re:[B' N' N] do:C bar ...
	-si:R' bar ...
	-si:C ] S:[C C N' N' N'] bar ...
	P MARK89 ];

%% BILLY

BILLY = [ ...
	~MARK5 DynMF fa:N' fa:N' fa:N sol:C fa:N mi:C bar ...
	fa:N' S:N' S:N re:C re:N mi:C bar ...
	fa:N' fa:N' fa:N sol:C fa:N mi:C bar ...
	fa:N' S:N' S:N S:[C C] re:C mi:C bar ...
	MARK9 fa:N sol:C fa:N mi:C fa:N mi:C re:N mi:C bar ...
	fa:N sol:C fa:N mi:C fa:N S:[C C] re:C mi:C bar ...
	fa:N' fa:N sol:C fa:N mi:C re:N mi:C bar ...
	fa:N' S:[N' B'] bar ...
	MARK13 sol:N' sol:N' la:N' sol:N' bar ...
	fa:N mi:C re:N mi:C fa:N' S:N fa:C bar ...
	sol:N' sol:N' la:N' sol:N' bar ...
	~[ fa:[N' N] mi:C re:N' ] S:N' bar ...
	MARK17 sol:N' sol:N' la:N' sol:N' bar ...
	fa:N mi:C re:N mi:C fa:N' S:N mi:C bar ...
	fa:N' fa:N' la:N' fa:N' bar ...
	mi:B' S:N' S:N DynF Note('+') do:C bar ...
	MARK21 re:N' do:N re:C do:N' -la:N' bar ...
	-sol:B' S:N' S:C -si:C do:C bar ...
	re:N' do:N re:C do:N' -la:N' bar ...
	-sol:B' S:N' S:C -si:C do:C bar ...
	re:N' fa:N' fa:B' bar ...
	MARK26 ~fa:B' fa:N mi:N re:N bar ...
	mi:N' -si:N re:[C B'] bar ...
	~re:N' -fa:N' re:N' do:N' bar ...
	~[ re:[B' N' N] do:C bar ...
	-si:[B' N' N] -la:C bar ...
	MARK31 -fa:[B' B] ] S:N bar ...
	~MARK60 P Note('') ...
	DynMF fa:N' fa:N' fa:N sol:C fa:N mi:C bar ...
	fa:N' S:N' S:N re:C re:N mi:C bar ...
	fa:N' fa:N' fa:N sol:C fa:N mi:C bar ...
	MARK64 fa:N' S:N' S:N S:[C C] re:C mi:C bar ...
	fa:N sol:C fa:N mi:C fa:N mi:C re:N mi:C bar ...
	fa:N sol:C fa:N mi:C fa:N mi:C re:N mi:C bar ...
	fa:N sol:C fa:N mi:C fa:N mi:C re:N mi:C bar ...
	MARK68 fa:N' S:N' S:B' bar ...
	sol:N' sol:N' la:N' sol:N' bar ...
	fa:N mi:C re:C mi:N fa:N' S:N fa:C bar ...
	sol:N' sol:N' la:N' sol:N' bar ...
	MARK72 ~[ fa:[N' N] mi:C re:[N' N] ] S:C bar ...
	sol:N' sol:N' la:N' sol:N' bar ...
	fa:N mi:C re:N mi:C fa:N' S:N fa:C bar ...
	fa:N' fa:N' la:N' mi:N' bar ...
	MARK76 mi:[B' N'] S:[C C] DynFF Note('+') do:C bar ...
	re:N' do:N re:C do:N' -la:N' bar ...
	-sol:B' S:[N' C] -si:C do:C bar ...
	re:N' do:N re:C do:N' -la:N' bar ...
	-sol:B' S:[N' C] -si:C do:C bar ...
	MARK81 re:N' fa:N' fa:B' bar ...
	~fa:B' fa:N mi:N re:N bar ...
	mi:N' -si:N re:[C B'] bar ...
	~re:N' -fa:N' re:N' do:N' bar ...
	MARK85 ~[ -si:[B' N' N] -la:C bar ...
	-fa:R' bar ...
	-fa:C ] S:[C C N' N' N' ] bar ...
	P MARK89 ];

%% MANDOLINE

MANDOLINE = [ ...
	DynP Note('+') ( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	MARK5 ( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	MARK9 ( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	MARK13 ( [mi si +mi +sol +mi si mi si +mi +sol +mi si].*C )/[ -mi:B' -mi:B' ] bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	( [mi si +mi +sol +mi si mi si +mi +sol +mi si].*C )/[ -mi:B' -mi:B' ] bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	MARK17 ( [mi si +mi +sol +mi si mi si +mi +sol +mi si].*C )/[ -mi:B' -mi:B' ] bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	( [la +do +fa +la +fa +do la +do +fa +la +fa +do].*C )/[ -fa:B' -fa:B' ] bar ...
	( [la +do +fa +la +fa +do la +do +fa +la +fa +do].*C )/[ -la:B' -la:B' ] bar ...
	MARK21 -si+si:B' S:B' bar ...
	P P ...
	S:N Note('') re:N sol:N la:N si:N +re:N bar ...
	re:N fa:N si:N +re:B' bar ...
	MARK26 re:N fa:N si:N +mi:B' bar ...
	solD:N si:N +mi:N +fa:B' bar ...
	sol:N si:N +mi:N +fa:B' bar ...
	DynP Note('+') ( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	MARK31 ( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	-la+la:B' S:[N' N'] bar ...
	P P ...
	MARK36 ~MARK51 P ...
	S:N Note('') re:N sol:N la:N si:N +re:N bar ...
	re:N fa:N si:N +re:B' bar ...
	re:N fa:N si:N +mi:B' bar ...
	solD:N si:N +mi:N +fa:B' bar ...
	MARK56 sol:N si:N +mi:N +fa:B' bar ...
	DynMP Note('+') ( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	MARK60 ( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	-la+la:B' S:[N' N'] bar ...
	P P ...
	MARK64 ~MARK68 P ...
	DynMP ( [mi si +mi +sol +mi si mi si +mi +sol +mi si].*C )/[ -mi:B' -mi:B' ] bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	( [mi si +mi +sol +mi si mi si +mi +sol +mi si].*C )/[ -mi:B' -mi:B' ] bar ...
	MARK72 ( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -fa:B'] bar ...
	( [mi si +mi +sol +mi si mi si +mi +sol +mi si].*C )/[ -mi:B' -mi:B' ] bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	( [la +do +fa +la +fa +do la +do +fa +la +fa +do].*C )/[ -fa:B' -fa:B' ] bar ...
	MARK76 ( [la +do +fa +la +fa +do la +do +fa +la +fa +do].*C )/[ -la:B' -la:B' ] bar ...
	re:B' S:[N' N'] bar ...
	P P ...
	S:N Note('') DynF re:N sol:N la:N si:N +re:N bar ...
	MARK81 re:N fa:N si:N +re:B' bar ...
	re:N fa:N si:N +mi:B' bar ...
	solD:N si:N +mi:N +fa:B' bar ...
	sol:N si:N +mi:N +fa:B' bar ...
	MARK85 DynMP Note('+') ( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	( [fa si +re +fa +re si +mi +re si +fa +re si].*C )/( -si:R' ) bar ...
	( [fa si +re +fa +re si fa si re fa re si].*C )/[ -si:B' -si:B'] bar ...
	P MARK89 ];

%% PIANO

PIANO_MD = [ ...
	~MARK21 Note('-') fa+la++re:B' fa+la++re:B' bar ...
	( re+sol+si:R' )/[ S:B' sol:N' si:N' ] bar ...
	fa+la++re:B' mi+la++do:B' bar ...
	S:N re:N sol:N la:N si:N +re:N bar ...
	( fa:R' )/[ la+si++re:B' re++re:N' si:N' ] bar ...
	MARK26 ( do+fa:R' )/[ la:B' mi++mi:N' la:N' ] bar ...
	fa+si:B' fa++fa:N' re+si:N' bar ...
	( sol:R' )/[ S:N -si+si:N mi++mi:N fa++fa:B' ] bar ...
	~MARK46 P*3 ...
	DynF la++re++fa:B' la+re++fa:B' bar ...
	mi+si++re:B' mi:N' si:N' bar ...
	MARK51 la+re+fa:B' la+do+mi:B' bar ...
	S:N re:N sol:N la:N si:N +re:N bar ...
	( fa:R' )/[ la+si++re:B' re++re:N' si:N' ] bar ...
	( do+fa:R' )/[ la:B' mi++mi:N' la:N' ] bar ...
	fa+si:B' fa++fa:N' re+si:N' bar ...
	MARK56 ( sol:R' )/[ S:N -si+si:N mi++mi:N fa++fa:B' ] bar ...
	3*P MARK60 ~MARK76 P ...
	DynFF la++re++fa:B' la++re++fa:B' bar ...
	sol+si++re:B' sol:N' si:N' bar ...
	la++re++fa:B' la++do++mi:B' bar ...
	S:N re:N sol:N la:N si:N +re:N bar ...
	MARK81 ( fa:R' )/[ la+si++re:B' re++re:N' si:N' ] bar ...
	( do+fa:R' )/[ la:B' mi++mi:N' la:N' ] bar ...
	fa+si:B' fa++fa:N' re+si:N' bar ...
	( sol:R' )/[ S:N -si+si:N mi++mi:N fa++fa:B' ] bar ...
	MARK85 ];

PIANO_MG = [ ...
	~MARK21 Note('--') -si+si:B' -si+si:B' bar ...
	-sol+sol:R' bar ...
	-si+si:B' -la+la:B' bar ...
	-sol+sol:R' bar ...
	-si+si:[B' N'] re++re:N' bar ...
	MARK26 -la+la:[B' N'] re++re:N' bar ...
	-solD+solD:[B' N'] -mi+mi:N' bar ...
	-sol+sol:R' bar ...
	~MARK46 P*3 ...
	-re+re:B' -re+re:B' bar ...
	-sol+sol:R' bar ...
	MARK51 re++re:B' -la+la:B' bar ...
	-sol+sol:R' bar ...
	-si+si:[B' N'] re++re:N' bar ...
	-la+la:[B' N'] re++re:N' bar ...
	-solD+solD:[B' N'] mi:N' bar ...
	MARK56 -sol+sol:R' bar ...
	3*P MARK60 ~MARK76 P ...
	DynFF -re+re:B' -re+re:B' bar ...
	-sol+sol:R' bar ...
	re++re:B' -la+la:B' bar ...
	-sol+sol:R' bar ...
	MARK81 -si+si:[B' N'] re++re:N' bar ...
	-la+la:[B' N'] re++re:N' bar ...
	-solD+solD:[B' N'] mi:N' bar ...
	-sol+sol:R' bar ...
	MARK85 ];

%% HARP

HARP_MD = [ ...
	~MARK31 2*P DynMF -la+re+fa:'$':[B' N'] mi:N' bar ...
	fa:B' S:N' +re++mi++sol:'$':N' bar ...
	la++re++fa:'$':[B' N'] la++do++mi:'$':N' bar ...
	MARK36 la++re++fa:'$':B' S:N -la:C re:N do:C bar ...
	-la+re+fa:'$':[B' N'] mi:N' bar ...
	fa:B' S:N' si++re++mi++sol:'$':N' bar ...
	la++re++fa:'$':[B' N'] la++do++mi:'$':N' bar ...
	la++re++fa:'$':R' bar ...
	MARK41 si++re++mi++sol:'$':R' bar ...
	S:R' bar ...
	si++re++mi++sol:'$':R' bar ...
	si++re++fa:'$':R' bar ...
	si++re++mi++sol:'$':R' bar ...
	MARK46 S:R' bar ...
	+do++fa:R' bar ...
	+do++mi:R' bar ...
	P*2 MARK51 ~MARK60 P ...
	DynMP -la+re+fa:'$':[B' N'] mi:N' bar ...
	fa:B' S:N' +re++mi++sol:'$':N' bar ...
	la++re++fa:'$':[B' N'] la++do++mi:'$':N' bar ...
	MARK64 la++re++fa:'$':B' S:N -la:C re:N do:C bar ...
	-la+re+fa:'$':[B' N'] mi:N' bar ...
	fa:B' S:N' si++re++mi++sol:'$':N' bar ...
	la++re++fa:'$':[B' N'] la++do++mi:'$':N' bar ...
	MARK68 la++re++fa:'$':R' bar ...
	si++re++mi++sol:'$':R' bar ...
	S:R' bar ...
	si++re++mi++sol:'$':R' bar ...
	MARK72 -si+re+fa:'$':R' bar ...
	mi+sol:R' bar ...
	S:R' bar ...
	do+fa:R' bar ...
	MARK76 do+mi:R' bar ...
	4*P MARK81 ];

HARP_MG = [ ...
	~MARK41 Note('-') +mi:R' bar ...
	-si+si:R' bar ...
	+mi:R' bar ...
	si++fa:R' bar ...
	mi:R' bar ...
	MARK46 -si+si:R' bar ...
	+fa++la:R' bar ...
	la++mi:R' bar ...
	2*P MARK51 ~MARK68 P ...
	+mi:R' bar ...
	-si+si:R' bar ...
	+mi:R' bar ...
	MARK72 si++fa:R' bar ...
	mi+si:R' bar ...
	-si+si:R' bar ...
	fa+la:R' bar ...
	MARK76 -la+mi:R' bar ...
	4*P MARK81 ];

%% BASS

BASS = [ ...
	~MARK21 Note('--') DynF si:B' si:B' bar ...
	sol:R' bar ...
	si:B' la:B' bar ...
	sol:R' bar ...
	si:[B' N'] +re:N' bar ...
	MARK26 la:[B' N'] +re:N' bar ...
	solD:[B' N'] mi:N' bar ...
	sol:R' bar ...
	si:C S:C si:N fa:C la:C si:C S:C si:N fa:C la:C bar ...
	si:C S:C si:N [fa la +re +do si +do si la].*C bar ...
	MARK31 si:C S:C si:N fa:C la:C si:C S:C si:N fa:C la:C bar ...
	si:C S:C si:N fa:C la:C si:C S:C si:B bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	MARK36 +re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	MARK41 +mi:R' bar ...
	si:R' bar ...
	+mi:R' bar ...
	si:R' bar ...
	+mi:R' bar ...
	MARK46 si:R' bar ...
	+fa:[B' N'] +sol:N' bar ...
	+la:R' bar ...
	+re:B' +re:B' bar ...
	+sol:B' +sol:B' bar ...
	MARK51 +re:B' la:B' bar ...
	sol:B' sol:B' bar ...
	si:[B' N'] +re:N' bar ...
	la:[B' N'] +re:N' bar ...
	solD:[B' N'] mi:N' bar ...
	MARK56 sol:R' bar ...
	si:C S:C si:N fa:C la:C si:C S:C si:N fa:C la:C bar ...
	si:C S:C si:N [fa la +re +do si +do si la].*C bar ...
	si:C S:C si:N fa:C la:C si:C S:C si:N fa:C la:C bar ...
	MARK60 si:C S:C si:N [fa la +re +do si +do si la].*C bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	MARK64 +re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	+re:[B' N'] S:N' bar ...
	MARK68 +re:[B' N'] S:N' bar ...
	+mi:R' bar ...
	si:R' bar ...
	+mi:R' bar ...
	MARK72 si:R' bar ...
	+mi:R' bar ...
	si:R' bar ...
	+fa:[B' N'] +sol:N' bar ...
	MARK76 +la:R' bar ...
	DynFF +re:B' +re:B' bar ...
	+sol:B' +sol:B' bar ...
	+re:B' la:B' bar ...
	sol:B' sol:B' bar ...
	MARK81 si:[B' N'] +re:N' bar ...
	la:[B' N'] +re:N' bar ...
	solD:[B' N'] +re:N' bar ...
	sol:R' bar ...
	MARK85 DynMF si:C S:C si:N fa:C la:C si:C S:C si:N fa:C la:C bar ...
	si:C S:C si:N [fa la +re +do si +do si la].*C bar ...
	si:C S:C si:N fa:C la:C si:C S:C si:N fa:C la:C bar ...
	P MARK89 ];

%% DRUMS

% Hi Hat (+la)
RIFF = [ V-1:N' S:[N' B'] bar ];
HIHAT = [ ...
	~MARK5 DynPP RIFF P RIFF P ...
	MARK9 RIFF P RIFF P ...
	MARK13 RIFF P*3 ...
	MARK17 P*2 RIFF P ...
	MARK21 ~MARK76 P ...
	V-2:N' S:[N' B'] bar ...
	P ...
	V-2:N' S:N' V-2:N' S:N' bar ...
	V-2:N S:[C N' B'] bar ...
	MARK81 ~MARK85 P*3 ...
	V-1:N' S:[N' N' N'] MARK89 ];

% Ride Cymbal (+sol)
RIDECYMBAL = [ ...
	~MARK60 P ...
	S:[N' N] V:C S:N V:C S:C V:N bar ...
	S:N V:C S:C V:N S:[N' N'] bar ...
	S:[N' N] V:C S:N V:C S:C V:N bar ...
	MARK64 S:N V:C S:C V:N S:[N' N'] bar ...
	S:[N' N] V:C S:N V:C S:C V:N bar ...
	S:N V:C S:C V:N S:[N' N'] bar ...
	S:[N' N] V:C S:N V:C S:C V:N bar ...
	MARK68 S:N V:C S:C V:N S:[N' N'] bar ...
	P*3 MARK72 ];
	
% Crash Cymbal (+fa)
RIFF1_1 = [ V:N' V:N' V:N' S:N' bar ];
RIFF1_2 = [ V:N' V:N' V:N' S:N V:C bar ];
RIFF1_3 = [ V:N' V:N' V:N' S:C V:C V:C bar ];
RIFF2_1 = [ V:N' V:N' V:N' V:N V:C bar ];
RIFF2_2 = [ V:N' V:N' V:N (V:C)*4 bar ];
CRASHCYMBAL = [ ...
	~MARK31 P P RIFF1_1 RIFF1_2 RIFF1_2 ...
	MARK36 RIFF1_2 RIFF1_1 RIFF1_2 RIFF1_2 RIFF1_3 ...
	MARK41 V:N' V:N' V:N' V:N V:C bar ...
	V:N' V:N' V:N V:C V:C V:C V:C bar ...
	V:N' V:N' V:N' V:N V:C bar ...
	V:N' V:N' V:N V:C V:N V:C bar ...
	V:N' V:N' V:N' V:N V:C bar ...
	MARK46 V:N' V:N' V:N' V:C V:C V:C bar ...
	V:N' V:N' V:N' V:N V:C bar ...
	V:N' V:N' V:N' V:N V:C bar ...
	V:N V:C S:C V:N V:N V:C S:C V:N bar ...
	V:N V:C S:C V:N V:N V:C S:C V:N bar ...
	MARK51 V:N V:C S:C V:N V:N V:C S:C V:N bar ...
	V:N V:C S:C V:N V:N V:C S:C V:N bar ...
	V:N V:C S:C V:N V:N V:C S:C V:C V:C bar ...
	V:N V:C S:C V:N V:N V:C S:C V:N bar ...
	V:N V:C S:C V:N V:N V:C S:C V:C V:C bar ...
	MARK56 Note( 'cresc', B', 'f', B' ) V:N V:C S:C V:N V:N S:[C N'] bar ...
	V:N' S:C V:C V:C V:N' S:C V:C V:C bar ...
	V:N' S:C V:C V:C V:N V:C S:C V:N bar ...
	V:N' S:C V:C V:C V:N' S:C V:C V:C bar ...
	MARK60 V:N' S:C V:C V:C V:N V:C S:C V:N bar ...
	DynMF V:N' S:N V:C V:N V:C S:C V:N bar ...
	V:N S:[C C N] V:N V:C S:C V:N bar ...
	V:N' S:[N C] V:N S:[C C N] bar ...
	MARK64 V:N S:[C C N] V:N V:C S:C V:N bar ...
	V:N' S:[N C] V:N S:[C C N] bar ...
	V:N S:[C C N] V:N V:C S:C V:N bar ...
	V:N' S:[N C] V:N S:[C C N] bar ...
	MARK68 V:N S:[C C N N C C C C] bar ...
	V:N V:C S:C V:C V:C V:N V:C S:C V:C V:C bar ...
	V:N V:C S:C V:C V:C V:N V:C S:C V:N bar ...
	V:N V:C S:C V:C V:C V:N V:C S:C V:C V:C bar ...
	MARK72 V:N V:C S:C V:C V:C V:N V:C S:C V:N bar ...
	V:N' S:C V:C V:C V:N V:C S:C V:N bar ...
	V:N' S:C V:C V:C V:N V:C S:C V:N bar ...
	V:N' S:C V:C V:C V:N V:C S:C V:C V:C bar ...
	MARK76 V:N' S:C V:C V:C V:N V:C S:[C C C] bar ...
	DynFF S:[N' C] V:C V:C V:N' S:C V:C V:C bar ...
	V:N V:C S:C V:N V:N V:C S:C V:N bar ...
	S:[N' C] V:C V:C S:N' S:C V:C V:C bar ...
	S:N V:C S:C V:C V:C V:N V:C S:C V:N bar ...
	MARK81 V:N V:C S:C V:N V:N V:C S:C V:N bar ...
	V:N V:C S:C V:N V:N V:C S:C V:N bar ...
	V:N' S:C V:C V:C V:N V:C S:C V:C V:C bar ...
	V:N V:C S:C V:C V:C V:N V:C S:C V:N bar ...
	MARK85 ];

% High Tom (+re)
HIGHTOM = [ ...
	~MARK68 S:[N C C N] V:N S:[C C C C] bar P*3 ...
	MARK72 ];

% Hi-Mid Tom (+do)
RIFF1 = [ S:[N C] V:C S:[N N C] V:C S:N bar ];
RIFF2 = [ S:[N C] V:N S:[C N C] V:C S:N bar ];
HIMIDTOM = [ ...
	~MARK46 P*3 RIFF1 RIFF1 ...
	MARK51 RIFF1*5 ...
	MARK56 Note( 'cresc', B', 'f', B' ) RIFF1*4 ...
	MARK60 RIFF1 DynMF RIFF2 RIFF1 RIFF2 ...
	MARK64 RIFF1 RIFF2 RIFF1 RIFF2 ...
	MARK68 RIFF1*4 ...
	MARK72 RIFF1*4 ...
	MARK76 RIFF1 DynFF RIFF1*4 ...
	MARK81 RIFF1*4 ...
	MARK85 ];

% Low-Mid Tom (si)
RIFF0 = [ V:N' V:N V:C V:N' S:[N C] bar ];
RIFF1 = [ S:N' V:N V:C V:N' S:[N C] bar ];
RIFF2 = [ V:N' V:N' V:N' S:N' bar ];
RIFF3 = [ (V:C)*12 bar ];
RIFF4 = [ S:[N C C N] V:N V:C S:C V:C S:C bar ];
LOWMIDTOM = [ ...
	~MARK5 DynPP P RIFF0 P RIFF0 ...
	MARK9 P*3 RIFF1 ...
	MARK13 P RIFF2 P RIFF1 ...
	MARK17 P RIFF1 P RIFF1 ...
	MARK21 DynMF ~MARK26 DynPP P*3 RIFF3 RIFF3 ...
	MARK31 RIFF3 RIFF3 P*3 ...
	MARK36 ~MARK56 Note( 'cresc', B', 'f', B' ) RIFF4 P*3 ...
	MARK60 DynMF ~MARK68 S:[N C C N N] V:C S:[C C C] bar P*3 ...
	MARK72 ~MARK76 S:[N' N' N' C] V:C S:C bar P*4 ...
	MARK81 ];

% Low Tom (la)
LOWTOM = [ ...
	~MARK5 DynPP P ...
	S:[N' N' N'] V:N V:C bar ...
	P ...
	S:[N' N' N'] V:N' bar ...
	MARK9 P ...
	S:[B' N'] V:N' bar ...
	P ...
	S:[N' N' N'] V:N V:C bar ...
	MARK13 P ...
	S:[N' N' N'] V:N' bar ...
	P ...
	S:[N' N' N'] V:N V:C bar ...
	MARK17 P ...
	S:[N' N' N'] V:N V:C bar ...
	P ...
	S:[N' N' N'] V:N V:C bar ...
	MARK21 ~MARK68 DynMF ...
	S:[N' N' N' C] V:C V:C bar ...
	P*3 ...
	MARK72 ~MARK76 ...
	S:[N' N' N' N] V:C bar ...
	P*4 ...
	MARK81 ];

% High Floor Tom (fa)
RIFF1 = [ V:N' S:[N' B'] bar ];
RIFF2 = [ V:N V:N S:N V:N V:N S:N bar ];
RIFF3 = [ V:N V:C V:N' V:N' S:N' bar ];
RIFF4_1 = [ V:N V:C V:N' V:N V:N S:[C C] bar ];
RIFF4_2 = [ V:N V:C V:N' V:N V:N V:C V:C bar ];
RIFF4_3 = [ V:N V:C V:N' V:N V:N V:N bar ];
RIFF5_1 = [ (V:N)*6 bar ];
RIFF5_2 = [ (V:N)*5 V:C V:C bar ];
HIGHFLOORTOM = [ ...
	~MARK5 DynPP RIFF1 P RIFF1 P ...
	MARK9 RIFF1 P RIFF1 P ...
	MARK13 RIFF1 P RIFF1 P ...
	MARK17 RIFF1 P RIFF1 P ...
	MARK21 DynMF RIFF2*5 ...
	MARK26 RIFF2*3 DynMF RIFF3*2 ...
	MARK31 RIFF3*2 RIFF4_1 RIFF4_2 RIFF4_1 ...
	MARK36 RIFF4_1 RIFF4_1 RIFF4_2 RIFF4_1 RIFF4_1 ...
	MARK41 RIFF4_1 RIFF4_3 RIFF4_1 RIFF4_1 RIFF4_1 ...
	MARK46 RIFF4_3 RIFF4_1 RIFF4_1 RIFF5_1 RIFF5_1 ...
	MARK51 RIFF5_1*3 RIFF5_2 RIFF5_1 ...
	MARK56 Note( 'cresc', B', 'f', B' ) RIFF5_1*4 ...
	MARK60 RIFF5_1 DynMF RIFF5_1*3 ...
	MARK64 RIFF5_1*4 ...
	MARK68 RIFF5_1*4 ...
	MARK72 RIFF5_1*4 ...
	MARK76 RIFF5_1 DynFF RIFF5_1*4 ...
	MARK81 RIFF5_1*4 ...
	MARK85 DynMF RIFF2*3 V:N' S:[N' N' N'] bar MARK89 ];

%% CACOFONIX

cacofonix( 'OnTheRise', 'Tempo', 192, 'Velocity', linspace( 50, 126, 8 ), ...
	MAIN, ...
	'Oboe', OBOE, ...
	'String Ensemble 2', STRINGS, ...
	'Alto Sax', BILLY, ...
	'Clarinet', PENNY, ...
	'Nylon String Guitar', MANDOLINE, ...
	'Acoustic Grand Piano', PIANO_MD / PIANO_MG, ...
	'Orchestral Harp', HARP_MD / HARP_MG, ...
	'Acoustic Bass', BASS, ...
	'Closed Hi-Hat', HIHAT, ...
	... % 'Ride Cymbal 1', RIDECYMBAL, ...
	... % 'Crash Cymbal 1', CRASHCYMBAL, ...
	'High Tom', HIGHTOM, ...
	'Hi-Mid Tom', HIMIDTOM, ...
	'Low-Mid Tom', LOWMIDTOM, ...
	'Low Tom', LOWTOM, ...
	'High Floor Tom', [ Note('dynamics*', 'p' ) HIGHFLOORTOM ] );
