%#ok<*BDSCA>
clc

NoteInit_fr

MARKER_INTRO = Note( 'Marker', 'Intro' );
MARKER_A = Note( 'Marker', 'A' );
MARKER_B = Note( 'Marker', 'B' );
MARKER_C = Note( 'Marker', 'C' );

MARKER_END = Note( 'Marker', 'END' );

%% Melody

Melody_Intro = [ MARKER_INTRO Note('+') S:B' bar S:B' bar ];

Melody = [ MARKER_A [ S:B' bar ]*6 ...
	MARKER_B ~[ re:C fa:C +re:B ] bar ...
	~[ re:C fa:C +re:B ] bar ...
	MARKER_END +mi:N' ~[ +fa:C +mi:C +fa:C ] bar ...
	~[ +mi:C +do:C ] la:B bar ...
	la:N re:N ~[ fa:C sol:C ] bar ...
	la:B' bar ...
	la:N re:N ~[ fa:C sol:C ] bar ...
	mi:B' bar ...
	MARKER_C ~[ re:C fa:C +re:B ] bar ...
	~[ re:C fa:C +re:B ] bar ...
	+mi:N' ~[ +fa:C +mi:C +fa:C ] bar ...
	~[ +mi:C +do:C ] la:B bar ...
	la:N re:N ~[ fa:C sol:C ] bar ...
	la:B la:N bar ...
	re:B' bar ...
	~re:B' bar ];

%% ORGAN

ORGAN_MD_INTRO = [ MARKER_INTRO ...
	S:N fa+la:'.':N fa+la:'.':N bar ...
	S:C mi:C sol+si:B bar ...
	];

ORGAN_MD = [ ...
	MARKER_A S:N la++do:'.':N la++do:'.':N bar ...
	S:C mi:C sol+si:B bar ...
	S:N fa+la:'.':N fa+la:'.':N bar ...
	S:C mi:C sol+si:B bar ...
	S:N la++do:'.':N la++do:'.':N bar ...
	S:C mi:C sol+si:B bar ...
	MARKER_B S:N fa+la:'.':N fa+la:'.':N bar ...
	S:C mi:C sol+si:B bar ...
	MARKER_END S:N la++do:'.':N la++do:'.':N bar ...
	S:N sol+la:B bar ...
	S:N fa+la:'.':N fa+la:'.':N bar ...
	S:N do+la:B bar ...
	S:N fa+la:'.':N fa+la:'.':N bar ...
	S:N doD+la:B bar ...
	MARKER_C S:N fa+la:'.':N fa+la:'.':N bar ...
	S:N sol+si:B bar ...
	S:N la++do:'.':N la++do:'.':N bar ...
	S:N sol+la:B bar ...
	S:N fa+la:'.':N fa+la:'.':N bar ...
	S:N doD+la:B bar ...
	S:N fa+la:'.':N fa+la:'.':N bar ...
	S:C mi:C sol+si:B bar ...
	];

MG = [ B' bar ];
ORGAN_MG_INTRO = [ MARKER_INTRO Note('-') re.*MG mi.*MG ];

ORGAN_MG = [ ...
	MARKER_A fa.*MG mi.*MG ...
	re.*MG mi.*MG fa.*MG mi.*MG ...
	MARKER_B re.*MG mi.*MG MARKER_END fa.*MG mi.*MG ...
	siB.*MG fa.*MG siB.*MG la.*MG ...
	MARKER_C re.*MG mi.*MG fa.*MG mi.*MG ...
	siB.*MG la.*MG re.*MG mi.*MG ...
	];

%% TAMBOURINE

RIFF = [ S:N V:'>':N V:'>':N bar S:C V:C V:'>':C V:C V:'>':C S:C bar ];
% RIFF = [ S:N -faB:'>':N -faB:'>':N bar S:C -faB:C -faB:'>':C -faB:C -faB:'>':C S:C bar ];

TAMBOURINE_INTRO = [ MARKER_INTRO RIFF ];
TAMBOURINE = [ MARKER_A RIFF*3 MARKER_B RIFF MARKER_END RIFF*3 MARKER_C RIFF*4 ];

%% CACOFONIX

Coda = Note( 'Decresc', B'*8, '0' );

cacofonix( 'SongOfStorms.mid', 'Tempo', 200, ...
	'Piccolo', [ Melody_Intro Melody*2 Coda Melody|MARKER_END ], ...
	'Percussive Organ', [ ORGAN_MD_INTRO ORGAN_MD*2 Coda ORGAN_MD|MARKER_END ] / ...
	[ ORGAN_MG_INTRO ORGAN_MG*2 Coda ORGAN_MG|MARKER_END ], ...
	'Tambourine', [ TAMBOURINE_INTRO TAMBOURINE*2 Coda TAMBOURINE|MARKER_END ] );
