
%
% The Piano Duet
%
% Compositor: Danny Elfman
% From: Corpse Bride
%

%#ok<*BDSCA>
clc

NoteInit_fr

MAIN = [ ...
	Note( 'Tempo', 140 ) ...
	Note( [6 4] ) [R' bar]*7 ...
	Note( [3 4] ) B' bar ...
	Note( [6 4] ) [R' bar]*4 ...
	Note( [2 4] ) B bar ...
	Note( [6 4] ) [R' bar]*6 ...
	Note( [3 4] ) B' bar ...
	Note( [6 4] ) R' bar ...
	Note( [4 4] ) R bar ...
	Note( [3 4] ) B' bar ...
	Note( [6 4] ) R' bar ...
	Note( [4 4] ) [ R bar ]*5 ...
	Note( [6 4] ) [R' bar] ...
	Note( 'Tempo', 250 ) Note( [6 4] ) [R' bar]*19 ...
	Note( [4 4] ) [ R bar ]*3 ...
	];

EMILYMD = [ Note('+') ...
	mi:B re:N mi:B fa:N bar ...
	mi:B re:N do:N -si:B bar ...
	do:B -si:N do:N re:B bar ...
	mi:R do:N re:N bar ...
	mi:B re:N mi:N fa:B bar ...
	sol:B fa:N mi:B re:N bar ...
	do:[ R B ] bar ...
	~do:N -la:N -si:N bar ...
	do:B -si:N do:N re:B bar ...
	do:N -si:B' -la:N -si:N bar ...
	do:B -si:N do:N re:B bar ...
	do:[ R B ] bar ...
	-la:N -si:N bar ...
	do:B -si:N do:N re:B bar ...
	do:B -si:B -la:N -solD:N bar ...
	-la:[ R B ] bar ...
	~-la:[ R B ] bar ...
	Note('') S:[ B N N ] -la:N -si:N bar ...
	do:B -si:N do:N' re:N' bar ...
	mi:B' bar ...
	S:R' bar ...
	S:R bar ...
	S:N re:N mi:N bar ...
	fa:B mi:N re:N do:B bar ...
	re:R bar ...
	S:R bar ...
	S:[ N N ] re:N mi:N bar ...
	fa:N mi:N re:N do:N bar ...
	re:B -si:B bar ...
	re:[ R B ] bar ...
	[R' bar]*12 ...
	Note('-') la:B la:N la:B la:N bar ...
	la:B siB:N la:B la:N bar ...
	+do:B +do:N +do:B siB:N bar ...
	la:[ R B ] bar ...
	Note('') sol:B sol:N la:B siB:N bar ...
	la:B siB:C la:C fa:B' bar ...
	fa:B sol:C fa:C mi:B re:N bar ...
	do:C' do:D re:C' re:D mi:C' mi:D fa:N bar ...
	sol:C la:C siB:C +do:C +re:C +mi:C +siB:T +la:T +sol:T bar ...
	++do:R bar ...
	];

EMILYMG = [ ...
	Note( [6 4] ) [R' bar]*7 ...
	Note( [3 4] ) B' bar ...
	Note('') fa:[ R B ] bar ...
	mi:[ R B ] bar ...
	re:B' faD:B' bar ...
	reD:B' mi:B' bar ...
	~mi:B bar ...
	fa:B' faD:B' bar ...
	solD:[ R B ] bar ...
	(-fa:[ R B ])/[ fa:B' re:B' ] bar ...
	(-solD:[ R B ])/[ mi:B' re:B' ] bar ...
	--la+-mi+-la:[ R B ] bar ...
	S:R' bar ...
	S:B' bar ...
	S:R' bar ...
	S:R bar ...
	S:B' bar ...
	Note('-') fa+siB:B' re+fa:B' bar ...
	-re+-la:R bar ...
	S:R bar ...
	S:R bar ...
	sol++do:B fa+siB:B bar ...
	re+sol:R bar ...
	-re+-la+re:[ R B ] bar ...
	[R' bar]*13 ...
	Note('-3') re++re:[ R N ] re++re:N bar ...
	mi++mi:[ R N ] mi++mi:N bar ...
	fa++fa:[ R B ] bar ...
	sol++sol:[ R B ] bar ...
	fa++fa:B' re++re:B' bar ...
	siB++siB:[ R B ] bar ...
	S:R bar ...
	S:R bar ...
	S:R bar ...
	];

VICTORMD = [ ...
	[R' bar]*7 ...
	B' bar ...
	[R' bar]*4 ...
	B bar ...
	[R' bar]*6 ...
	Note('++') S:N -la:N -si:N bar ...
	do:B -si:N do:B re:N bar ...
	mi:R bar ...
	S:B' bar ...
	S:[ R B ] bar ...
	S:[ N N ] Note('+') re:N mi:N bar ...
	fa:N mi:N re:N do:N bar ...
	S:R bar ...
	S:R bar ...
	S:R bar ...
	S:R S:N S:C Note('++') re:C bar ...
	re:B re:N re:B re:N bar ...
	re:B miB:N re:B re:N bar ...
	fa:B fa:N fa:B miB:N bar ...
	re:N -siB:N -fa:N -re:B' bar ...
	~-re:[ R B ] bar ...
	do:B do:N re:B miB:N bar ...
	re:B' -siB:B' bar ...
	-siB:B do:C -siB:C -la:B -sol:N bar ...
	-re:N -faD:N -la:N re:N faD:N la:N bar ...
	+re:[ R B ] bar ...
	S:R' bar ...
	S:R' bar ...
	Note('+') la:C fa:C la:C fa:C re:C -la:C la:C fa:C la:C fa:C re:C -la:C bar ...
	la:C fa:C la:C fa:C re:C -la:C fa:N re:C mi:C fa:C la:C bar ...
	+do:C sol:C +do:C sol:C mi:C do:C +do:C sol:C +do:C sol:C mi:C do:C bar ...
	la:C fa:C la:C fa:C do:C -la:C la:C fa:C la:C fa:C do:C -la:C bar ...
	-sol:C re:C sol:C +re:C sol:N -sol:C re:C sol:C +re:C sol:N bar ...
	+do:C la:C +do:C la:C fa:C do:C +re:C la:C +re:C la:C fa:C re:C bar ...
	siB:C fa:C siB:C fa:C re:C -siB:C siB:C fa:C siB:C fa:C re:C -siB:C bar ...
	Note('++') sol:[ T T ] mi:[ T T ] do:[ T T ] sol:[ T T ] mi:[ T T ] do:[ T T ] bar ...
	S:R bar ...
	S:R bar ...
	];

VICTORMG = [ ...
	[R' bar]*7 ...
	B' bar ...
	[R' bar]*4 ...
	B bar ...
	[R' bar]*6 ...
	B' bar ...
	R' bar ...
	R bar ...
	B' bar ...
	R' bar ...
	R bar ...
	Note('') fa+siB:B re+fa:B bar ...
	re+faD:R bar ...
	S:R bar ...
	S:R bar ...
	S:[ R B ] bar ...
	Note('+') -sol:N re:N sol:N siB:N sol:N re:N bar ...
	 -sol:N re:N sol:N siB:N sol:N re:N bar ...
	-fa:N do:N fa:N la:N fa:N do:N bar ...
	siB:N fa:N re:N -siB:B' bar ...
	~-siB:[ R B ] bar ...
	Note('') -siB+sol:[ R B ] bar ...
	sol:N re:N -siB:N miB:B' bar ...
	-siB:B do:C -siB:C -la:B -sol:N bar ...
	faD:N re:N -la:N re:N -la:N -faD:N bar ...
	-re:[ R B ] bar ...
	la:N fa:N re:N la:N re:N -la:N bar ...
	la:N fa:N re:N la:N re:N -la:N bar ...
	la:N fa:N re:N la:N re:N -la:N bar ...
	la:N fa:N re:N la:N re:N -la:N bar ...
	sol:N mi:N do:N mi:N do:N -sol:N bar ...
	fa:N do:N -la:N -fa:N do:N fa:N bar ...
	S:[ R B ] bar ...
	S:[ R B ] bar ...
	S:[ R B ] bar ...
	S:R bar ...
	S:R bar ...
	S:R bar ...
	];


cacofonix( 'PianoDuet', 'Velocity', linspace( 25, 100, 8 ), MAIN, VICTORMD / VICTORMG, EMILYMD / EMILYMG );


