
%
% Victor's Piano Solo
%
% Compositor: Danny Elfman
% From: Corpse Bride
%

%#ok<*BDSCA>
clc

NoteInit_fr

PedON = Note( 'sustain', 'on' );
PedOFF = Note( 'sustain', 'off' );

faDD = Note('faDD');

MAIN = [ ...
	Note('Tempo', 50) S:C bar ...
	Note([4 4]) S:[B C] [ Note('fermata', C, N ) S:C ]*3 bar ...
	Note('Tempo', 76) Note([6 8]) [ S:B' bar ]*12 ...
	S:N' Note('rall', N', 70) S:N' bar ...
	Note('Tempo', 76) Note([6 8]) [ S:B' bar ]*13 ];


[fa,faN] = deal( faD, fa );
[do,doN] = deal( doD, do );
[sol,solN] = deal( solD, sol );
[re,reN] = deal( reD, re );

MD = [
	Note('+') DynPP Note('cresc',[C R],'p') +fa:C bar ...
	+solN:C +re:C +mi:C si:C +doN:C fa:C solN:C ~[ -sol+sol:C bar ...
	DynPP -sol+sol:B' bar ...
	-sol+sol:B' ] bar ...
	Note('+0') DynP sol:N ~sol:D sol:D sol:N ~sol:D sol:D bar ...
	sol:N ~sol:D la:D sol:N ~sol:D sol:D bar ...
	si:N ~si:D si:D si:N ~si:D la:D bar ...
	sol:B' bar ...
	fa:N ~fa:D fa:D sol:N ~sol:D la:D bar ...
	sol:N' mi:N' bar ...
	mi:N ~mi:D mi:D re:N do:C bar ...
	fa:N' fa++fa:N fa++fa:D fa++fa:D bar ...
	fa++fa:N +fa:D +fa:D +mi:N +re:C bar ...
	sol++do++sol:N +sol:D ~sol:D sol+siD++sol:C sol:D sol:D ~+sol:D +sol:D bar ...
	++sol:N sol:D ~+sol:D ++sol:C ~+sol:C sol:D +mi:'-':D bar ...
	DynMP mi++mi:N' re++re:N ~re++re:D do++do:D bar ...
	do++do:N' -siD+siD:N ~-siD+siD:D do++do:D bar ...
	do++do:N ~do++do:D do++do:D re++re:N ~re++re:D re++re:D bar ...
	mi++mi:N' Note('cresc',[N' B'],'mf') ~mi++mi:N ~mi++mi:D mi++mi:D bar ...
	mi++mi:N' fa++fa:N ~fa++fa:D si++sol:D bar ...
	si++mi++sol:B' bar ...
	DynP Note('cresc',[B' N'],'mp') +do++sol:N' laD++do++fa:N +mi:C bar ...
	+mi:C +reN:C +doN:C DynMP Note('cresc',[N' B' B'],'mf') re+faDD+laD:N +sol:C bar ...
	+sol:D ~sol:D sol:D ~+sol:D +sol:C +sol:D ~sol:D sol:D ~+sol:D +sol:C bar ...
	+sol:D ~sol:D sol:D ~+sol:D +la:C +sol:C +mi:C +do:C bar ...
	DynMF si++si:N si++si:C si++si:N si++si:C bar ...
	Note('cresc',[B' B'],'f') si++mi++si:N si++mi++si:C si++si:N la++la:C bar ...
	si++si:N' si++si:N sol+si++re++fa:D +mi++sol++si++re:D bar ...
	];

MG = [ ...
	Note('--') PedON S:C bar ...
	S:N' PedON S:B PedON S:C bar ...
	DynPP ~[ do:C PedON sol:C +do:C +mi:C +do:C sol:C ] bar ...
	PedON ~[ do:C sol:C +do:C +mi:C +do:C sol:C ] bar ...
	PedON ~[ do:C sol:C +do:C ] PedON ~[ +mi:C +do:C sol:C ] bar ...
	PedON ~[ do:C sol:C +do:C ] PedON ~[ +mi:C +do:C sol:C ] bar ...
	PedON ~[ -si:C fa:C si:C ] PedON ~[ +fa:C +re:C si:C ] bar ...
	PedON ~[ mi:C si:C +mi:C ] PedON ~[ +sol:C +mi:C si:C ] bar ...
	PedON ~[ fa:C +do:C +fa:C ] PedON ~[ ++do:C +la:C +fa:C ] bar ...
	PedON ~[ +do:C +sol:C ++do:C ] PedON ~[ la:C +mi:C +la:C ] bar ...
	PedON ~[ fa:C +do:C +fa:C ] PedON ~[ ++do:C +la:C +fa:C ] bar ...
	PedON ~[ si:C +fa:C +si:C ] PedON ~[ ++re:C +si:C +fa:C ] bar ...
	PedON ~[ ++re:C +si:C +fa:C ] PedON ~[ +si:C +fa:C +re:C ] bar ...
	PedON ~[ ++re:C ++sol:D ++re:D +sol:C ] PedON ~[ ++re:N +sol:C ] bar ...
	+sol:D ++sol:D ++re:D +sol:C' ~+sol:N' bar ...
	DynMP PedON ~[ do:C sol:C +do:C ] ~[ +sol:C +mi:C +do:C ] bar ...
	PedON ~[ +fa:C +do:C la:C ] PedON ~[ miD:C siD:C +miD:C ] bar ...
	PedON ~[ laD:C +miD:C +laD:C ] PedON ~[ sol:C +re:C +sol:C ] bar ...
	PedON ~[ +sol:D +mi:D +sol:D +mi:D +do:D sol:D ] PedON Note('cresc',[N' B'],'mf') ~[ +sol:D +mi:D +sol:D +mi:D +do:D sol:D ] bar ...
	PedON ~[ +sol:D +mi:D +sol:D +mi:D +do:D sol:D ] PedON ~[ +si:D +fa:D +si:D +fa:D +re:D si:D ] bar ...
	PedON ~[ mi:C si:C +mi:C ] PedON ~[ +sol:C +mi:C si:C ] bar ...
	DynP Note('cresc',[B' N'],'mp') PedON +do:N' PedON fa:N' bar ...
	PedON la:N' DynMP Note('cresc',[N' B' B'],'mf') PedON re:N' bar ...
	PedON +la+++do+++mi:N' PedON +sol+++do+++mi:N' bar ...
	PedON +fa++la+++reN:N' PedON +sol+++do+++mi:N +mi:D +do:D bar ...
	PedON ~[ ++fa:D ++re:D +si:D +fa:D +si:D ++re:D ] PedON ~[ ++fa:D ++re:D ++sol:D ++re:D ++la:D ++re:D ] bar ...
	Note('cresc',[B' B'],'f') PedON ~[ +doN:D solN:D ++doN:D ++mi:D ++doN:C ] PedON ~[ faN:D +doN:D faN:D +la:D +faN:C ] bar ...
	PedON ~[ reN:D la:D +reN:D +faN:D +la:D ++reN:D ] PedON ~[ ++faN:D ++re:D +si:D +la:D ] PedOFF +mi++sol++si+++re:D +la+++re+++fa+++la:D bar ...
	];

cacofonix( 'VictorsPianoSolo', 'Velocity', linspace( 25, 100, 8 ), MAIN, MD / MG );
